### ISSUE TITLE
Generate phive configuration file from composer.json

### ISSUE THREAD

**Issue by belanur** [phar-io/phive#10]
Scan ```composer.json``` and find tools that are listed in the phar.io repository list. Create an entry in ```phive.xml``` for each of these tools accordingly.

**Comment by theseer** [comment]
Todo:

* Add composer alias to repositories.xml
* Implement alias matcher
* Generate install list from that and show it to the user
* Suggest installation

**Comment by theseer** [comment]
Aliases added with commit https://github.com/phar-io/phar.io/commit/c9eb0fae18c23a9ead16de0d9b49e75cebeb7046
