### ISSUE TITLE
PHAR files are always symlinked on install, even with "-c" option

### ISSUE THREAD

**Issue by tommy-muehle** [phar-io/phive#108]
Hi,

I can no more copy PHAR files instead of symlinking. Tried it with "-c" and with "--copy" option.

<img width="945" alt="bildschirmfoto 2017-06-06 um 10 07 39" src="https://cloud.githubusercontent.com/assets/1351840/26819630/0c40100c-4aa0-11e7-96fc-1fe21b41ae32.png">

My environment:
* Phive 0.7.1
* PHP 7.1.5

Let me hear if more informations are needed. :)

**Comment by belanur** [comment]
Thanks for reporting the issue :) Copying should work again in version 0.7.2
