### ISSUE TITLE
Travis fails with 403

### ISSUE THREAD

**Issue by jaapio** [phar-io/phive#126]
For some reason my travis build fails with an 403 error. I can't repoduce this on my machine. Do you know a reason why this might happen?

The specific job:
https://travis-ci.org/phpDocumentor/phpDocumentor2/jobs/316622580

**Comment by theseer** [comment]
Github usually replies with a 403 if their API-Rate-Limit has been hit.

Interesting to have that happen on travis. One would except travis' IPs to be white listed.
We do have a ticket pending to allow custom github api tokens to not rely on that.

**Comment by jaapio** [comment]
It might be that this beta build stages machines are not whitelisted...

**Comment by theseer** [comment]
We might also add explicit support for Github's Rate-Limit to show a more helpful error message. I think we might open a ticket for that as well.

**Comment by theseer** [comment]
You might also add phive's home directory to the cache to reduce downloads/api calls.

I think there is nothing left for us to do here, so I'll close the ticket. Feel free to keep commenting :)

**Comment by theseer** [comment]
Short heads up: As of version [0.9.0](https://github.com/phar-io/phive/releases/tag/0.9.0) phive supports github auth tokens.

**Comment by jaapio** [comment]
Thanks for the heads up!
