### ISSUE TITLE
Invalid Getting PHIVE on phar.io

### ISSUE THREAD

**Issue by sergeyklay** [phar-io/phive#131]
There is misspelling in installation instructions on phar.io related to adding keys.

Steps to reproduce:

```
$ gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9B2D5D79
gpg: requesting key 9B2D5D79 from hkp server hkps.pool.sks-keyservers.net
gpgkeys: key 9B2D5D79 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm
````

Note: "gpg: no valid OpenPGP data found.".

But this works:

```
$ gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
gpg: requesting key 9B2D5D79 from hkp server hkps.pool.sks-keyservers.net
gpg: key 9B2D5D79: public key "phar.io <team@phar.io>" imported
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   3  signed:   3  trust: 0-, 0q, 0n, 0m, 0f, 3u
gpg: depth: 1  valid:   3  signed:   1  trust: 2-, 0q, 0n, 1m, 0f, 0u
gpg: next trustdb check due at 2018-08-19
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

```

**Comment by sergeyklay** [comment]
Also please take a look: https://lkml.org/lkml/2016/8/15/445

**Comment by theseer** [comment]
The documentation is indeed wrong. Or rather: Outdated. It used to work but since later (by now current) versions of gnupg enforce long key ids, this stopped working. I'll update the webpage asap.

Thank you for bringing this to our attention.

For what it's worth: We already have a ticket (#77) for ensuring that we are not using any short key ids anymore.

**Comment by theseer** [comment]
Website update: https://github.com/phar-io/phar.io/commit/32be5b6723abd8403bfa3cef2149ec15053a4a20
