### ISSUE TITLE
Impossible to import GPG keys

### ISSUE THREAD

**Issue by Aerendir** [phar-io/phive#135]
I'm trying to import into GPG the kesy used to verify the authenticity via GPG.

I'm using the suggested command

    gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79

But this returns an error

> gpg: ricezione dal keyserver fallita: No route to host

I've also tried those other commands that I guessed googling a bit:

    gpg --keyserver http://hkps.pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
    gpg: Non sono stati trovati dati OpenPGP validi.
    gpg: Numero totale esaminato: 0

And also

    curl -sSL https://phar.io/phive.phar.asc | gpg --import -
    gpg: Non sono stati trovati dati OpenPGP validi.
    gpg: Numero totale esaminato: 0

Nothing seems to work.

But lookingup the key on the GPG server, I can find it: http://hkps.pool.sks-keyservers.net/pks/lookup?op=get&search=0x9D8A98B29B2D5D79

How can I import this key in GPG?

**Comment by theseer** [comment]
You did everything correct. Judging on the error message

    gpg: ricezione dal keyserver fallita: No route to host
                                          ^^^^^^^^^^^^^^^^   
the server in the pool that you ended up at was/is not available. That can happen at times and is one of the reasons why we implemented the round robin lookup into phive.

Trying now, it works for me here:

```shell
theseer@nyda ~ $ gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
gpg: requesting key 9B2D5D79 from hkp server hkps.pool.sks-keyservers.net
gpg: key 9B2D5D79: "phar.io <team@phar.io>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

Nothing we can do here.

**Comment by Aerendir** [comment]
@theseer , nothing: it doesn't work :(

**Comment by theseer** [comment]
The last approach with curl can't work. You're trying to import a signature, not a key.

Try this:

```theseer@nyda ~ $ host hkps.pool.sks-keyservers.net```

You'll get a (long) list of A and AAAA records, something like this:

```
hkps.pool.sks-keyservers.net has address 94.142.242.225
hkps.pool.sks-keyservers.net has address 193.164.133.100
hkps.pool.sks-keyservers.net has address 92.43.111.21
hkps.pool.sks-keyservers.net has address 192.94.109.73
hkps.pool.sks-keyservers.net has address 68.187.0.77
hkps.pool.sks-keyservers.net has address 37.191.226.104
hkps.pool.sks-keyservers.net has address 193.224.163.43
hkps.pool.sks-keyservers.net has address 51.15.53.138
hkps.pool.sks-keyservers.net has address 216.66.15.2
hkps.pool.sks-keyservers.net has address 176.9.147.41
[...]
```

Since I don't know which host you end up on, you can now at least try by IP:
```
theseer@nyda ~ $ gpg --keyserver 94.142.242.225 --recv-keys 0x9D8A98B29B2D5D79
```

If that IP doesn't answer, try the next.
If all that doesn't work, your network has issues.

**Comment by Aerendir** [comment]
@theseer , in the end I did another search (this time it was a better search!) and I found this post:

https://medium.com/@xiaoxiaohou/gpg-keyserver-receive-failed-no-route-to-host-9e47a0dd83f8

So, doing

    gpg-connect-agent --dirmngr 'keyserver --hosttable'

I found other servers to connect to:

```console
Aerendir$ gpg-connect-agent --dirmngr 'keyserver --hosttable'
S # hosttable (idx, ipv6, ipv4, dead, name, time):
S #   0       hkps.pool.sks-keyservers.net
S #   .       hkps.pool.sks-keyservers.net
S #   .   --> 11 16 10 9 8 7 15 14 13 12 6 5* 4 3 2 1
S #   1 6     [2a02:c205:3001:3626::1] (mail.b4ckbone.de)
S #   2 6     [2a01:4a0:59:1000:223:9eff:fe00:100f] (oteiza.siccegge.de)
S #   3 6     [2606:1c00:2802::b]
S #   4 6     [2001:bc8:4700:2300::10:f15]
S #   5 6     [2001:738::600:216:3eff:fe02:42] (hufu.ki.iif.hu)
S #   6 6     [2001:470:1:116::6]
S #   7   4   216.66.15.2
S #   8   4   193.224.163.43 (hufu.ki.iif.hu)
S #   9   4   193.164.133.100 (mail.b4ckbone.de)
S #  10   4   192.94.109.73
S #  11   4   176.9.147.41 (ntzwrk.org)
S #  12   4   94.142.242.225 (sks.spodhuis.org)
S #  13   4   68.187.0.77 (stlhs.archreactor.org)
S #  14   4   51.15.53.138 (ams.sks.heypete.com)
S #  15   4   37.191.226.104 (host-37-191-226-104.lynet.no)
S #  16   4   18.9.60.141 (cryptonomicon.mit.edu)
OK
```

I picked `mail.b4ckbone.de`. So launching this command:

```console
Aerendir$ gpg --keyserver mail.b4ckbone.de --recv-keys 0x9D8A98B29B2D5D79
gpg: key 9D8A98B29B2D5D79: 4 signatures not checked due to missing keys
gpg: key 9D8A98B29B2D5D79: public key "phar.io <team@phar.io>" imported
gpg: non è stata trovata alcuna chiave definitivamente affidabile
gpg: Numero totale esaminato: 1
gpg:              importate: 1
```

Finally I was able to download the key!
