### ISSUE TITLE
Show key Ids for installed phars

### ISSUE THREAD

**Issue by ThomasWeinert** [phar-io/phive#138]
To make it easier to use Phive in the CI it would be good to have a way to show the key Ids needed for the `--trust-gpg-keys` flag. 

I added it to the `phive status` command as a test. 

![phive-keys](https://user-images.githubusercontent.com/236825/38768877-6b10165e-3ffa-11e8-926c-caee086db419.png)

Does that make sense or should it be a separate command?

**Comment by theseer** [comment]
I think that makes a LOT of sense and I like it.
We might argue about the name (keys ./. key ./. key id?) and information shown (fingerprint or id?)

But yes, please! :+1:
