### ISSUE TITLE
Broken progress output on Windows

### ISSUE THREAD

**Issue by ThomasWeinert** [phar-io/phive#144]
The download progress output for keys looks like this on Windows 10:

![phive-broken-progress](https://user-images.githubusercontent.com/236825/39958498-2a00064a-5604-11e8-8284-56486af6bbe6.png)

Strange enough it works just fine for the Phars. 

I was not able to find out why that happens. A workaround for now seems to be to not output a progress for small downloads (<3k).

**Comment by theseer** [comment]
Can't we just not support windows?

Kidding.
The only obviously thing would be the amount of digits required comparing small vs. larger downloads but I  don't see why that would make any difference at the output level?

**Comment by theseer** [comment]
For reference: It doesn't seem to make a difference whether `cmd.exe` or `powershell` is used. The output just garbled in a different way.
