### ISSUE TITLE
Skip GPG keys verification

### ISSUE THREAD

**Issue by Aerendir** [phar-io/phive#146]
I'm trying to install [phan/phan](https://github.com/phan/phan/) with this command:

```console
$ phive install https://github.com/phan/phan/releases/download/0.12.10/phan.phar
Phive 0.10.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://github.com/phan/phan/releases/download/0.12.10/phan.phar
[ERROR]    Failed to download load https://github.com/phan/phan/releases/download/0.12.10/phan.phar.asc: HTTP Code 404
```

As you can see, Phive fails to find the keys to verify the downloaded package: is there a way to skip this step or to fix it?

**Comment by theseer** [comment]
The Phan developers do not provide signed phar releases and thus Phan can not yet be installed with phive.

We are discussing options for insecure installations in #134.

**Comment by theseer** [comment]
If you feel like, you might consider opening a ticket with the Phan developers to sign their phars.

**Comment by Aerendir** [comment]
Ok, so currently it is not possible to skip verification, but you are discussing about: ok.

I'll anyway open a ticket on their repository to see if they like to add a GPG verification key...

**Comment by theseer** [comment]
For the record: The phan developers added a gpg signature and phan is now an officially supported alias.
