### ISSUE TITLE
Global PHARs should be installed to /usr/local/bin

### ISSUE THREAD

**Issue by filips123** [phar-io/phive#148]
Global PHARs should be installed to `/usr/local/bin` not to` /usr/bin`.

From [Unix Stackexchange](https://unix.stackexchange.com/a/8658):
> `/usr/local/bin` is for normal user programs not managed by the distribution package manager, e.g. locally compiled packages. You should not install them into `/usr/bin` because future distribution upgrades may modify or delete them without warning.

**Comment by theseer** [comment]
We probably should make that configurable. We already have a switching logic for MacOs I believe.

I personally consider `/usr/bin` a valid target directory. Even though it's not placed there by the OS package management system it's also not a locally compiled thing either but managed by `phive`.

**Comment by filips123** [comment]
Yes, this should be configurable.
