### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by jaapio** [phar-io/phive#152]
Because I'm not sure if you want to provide this, before creating a PR and put more effort in this I create this issue. I did some small steps to make phive work with docker. I think it would be nice to have a official image for phive at docker hub. 

The basic content of the docker file could be something like this:

```Dockerfile
FROM php:7.2

RUN apt-get update \
    && apt-get install --yes -q wget gpg \
    && cd /opt/ \
    && wget https://phar.io/releases/phive.phar \
    && wget https://phar.io/releases/phive.phar.asc \
    && gpg --yes --keyserver pool.sks-keyservers.net --recv-keys 0x9B2D5D79 \
    && gpg --yes --verify phive.phar.asc phive.phar \
    && chmod +x phive.phar \
    && mv phive.phar /usr/bin/phive

ENTRYPOINT ["/usr/bin/phive"]
```
In addition I created a bash script to make phive work like it is native installed on your working station.

```bash
#!/bin/bash

phive () {
    tty=
    tty -s && tty=--tty
    phiveHome=$HOME/.phive
    docker run \
        $tty \
        --interactive \
        --rm \
        --user $(id -u):$(id -g) \
        --volume /etc/passwd:/etc/passwd:ro \
        --volume /etc/group:/etc/group:ro \
        --volume $phiveHome:$phiveHome \
        --volume $(pwd):/app \
        --workdir /app \
        phar-io/phive:latest --home $phiveHome "$@"
}

phive "$@"
```
the script sets the phive home to a mounted directory so when symlink is created the actual symlink on the host filesytem is pointing to the right directory. This why phpstorm is able to index the phars so code inspections will just work. 

When you want to have this all in I will create an organisation on docker hub and configure it to build when a tag is pushed to github. And create a PR to add the dockerfile, and update the documentation how to run phive. 

For me it makes a lot of sense to have this since I don't have php installed on my laptop to prevent errors when mixing different phpversions in a project. I like to have everything dockerized.

**Comment by theseer** [comment]
I'm not sure why one would need a docker image with basically only phive in it, but I guess we could provide an official one for those who want it as an alternative means of distribution.

Rather than installing it like shown above though, I'd prefer it to be installed via an OS package. Which means we should provide at least RPM and DEB packages.

Regarding the Dockerfile: I'm not sure what image `php:7.2` would actually fetch and how much overhead comes along with it? If we are to provide a docker image, it should be as minimalistic as possible to do the job and nothing else.

**Comment by theseer** [comment]
I'm still neutral regarding a docker image.

If we are to have one, building and pushing it to docker hub needs to be fully automated as I don't want to deal with it upon release.

While add it, we probably should go and create RPM and DEB packages - at least until redhat/fedora and ubunutu/debian consider adding phive themselves. 

@jaapio You still feel like doing the docker stuff?

**Comment by jaapio** [comment]
I use the image myself. But I don't think it is wise to add it if you are not going to support it. I would like to have you with the setup but I am not involved in the maintenance of phive. So I won't be able to keep it up to date.

On the other side if you want to make a package for Linux, I think maintenance of the docker file is not really needed.

Please focus first on the real features of phive. If you need any help with docker in the future feel free to contact me. Most important for phive is the adoption in the php community.

**Comment by FiGOBLAC** [comment]
Any updates on this?

**Comment by icedream** [comment]
I would like to use the official Docker image as part of a GitLab Continuous Integration pipeline to install deployment-aiding tools like cachetool. Will be watching this. :+1:

**Comment by filips123** [comment]
There is one additional thing when this would be useful: When creating Docker images that need to contain PHIVE.

For example, you can already specify this in `Dockerfile` which will install Composer into your image:

```dockerfile
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
```

The same should be possible for PHIVE:

```dockerfile
COPY --from=phive:latest /usr/bin/phive /usr/bin/phive
```

The benefit of this is that you don't have to worry about the installation process, you just need to copy a file to your image.

**Comment by rgeraads** [comment]
Any update on this?

As for the minimalistic docker/php version, you could use `php:7.2-cli-alpine`

Supporting a docker image could lead to a more intuitive flow, since it doesn't need to be installed on bare metal.

**Comment by theseer** [comment]
At long last, we now have our first "official" phive container image on docker hub.

https://hub.docker.com/r/phario/phive

### Background

I tried to create a truly minimalistic image based off of Fedora 37. I still think the php cli binary shipping with Fedora is way to big, containing extensions that aren't needed but I'm too lazy to build PHP myself just to reduce the size by a fraction. 

In general, the image is 15 MB (compressed, uncompressed it's ~39 MB).  Maybe I give alpine a try as a base image to strip from at some point to reduce it further - in case alpine's PHP is smaller.

The image created comes  - for now ;) - with PHP 8.1.4, gnupg and a phar of phive 0.15.2-8.

Time to give it some test spins and provide feedback :-)
