### ISSUE TITLE
install --copy flag ignored

### ISSUE THREAD

**Issue by jaapio** [phar-io/phive#153]
When I have a project that has already some phars installed with an existing `phive.xml` I can use the install command to install the configured dependencies. But if I want to copy the dependencies for some reason I cannot do that. When a `phive.xml` exists the flag `--copy` seems to be ignored silently. 

I would expect that phive provides a warning that you are installing the phars in a different way that the project definition and accepts the `--copy` flag. If it changes the `phive.xml` file using any aditional flags that would be ok. This allows the user even to commit his changes when needed.

**Comment by theseer** [comment]
Good catch. Your suggestion makes sense.
