### ISSUE TITLE
Allow global installation of PHARs

### ISSUE THREAD

**Issue by belanur** [phar-io/phive#16]
By running ```phive install [pharname] -global```  a PHAR should be installed and made executable within the PHIVE home directory so it can be executed from any location.

**Comment by sagikazarmark** [comment]
I would make this a No.1 feature. At least I almost started to work on exactly the same project just to provide an easy way of installing phars globally. My idea was phars.io, thank god I checked phar.io as well. :smile:

**Comment by theseer** [comment]
You are very welcome to contribute a PR :)

**Comment by sebastianbergmann** [comment]
Since 78de4eecc856fa1dc47a3553bb36c2fa60aa6ae9 has been merged I think that this issue can be closed.

**Comment by belanur** [comment]
Right. Thank you for your contribution(s)! Feels great receiving PRs for this project :)
