### ISSUE TITLE
How to use PHPUnit with Phive

### ISSUE THREAD

**Issue by Aerendir** [phar-io/phive#160]
Downloading PHPUnit is a breeze with Phive, but, how do you write the tests if you don't have the classes downloaded through Composer?

A simple question to which I cannot find an answer :)

**Comment by theseer** [comment]
Just to make sure, let me state two things: Phive has nothing to do with running your tests or running PHPUnit. And Phive is also not a replacement for Composer when it comes to dealing with your software's runtime dependencies.

Now regarding PHPUnit and your tests: As a phar, PHPUnit contains with everything it needs to run. But to execute your tests, you obviously are going to need some form of autoloading in place for _your_ classes. `PHPUnit` will take care of loading its own classes just fine.

To have your classes autoloaded, you can use Composer's Autoloader or any other.

**Comment by Aerendir** [comment]
Ok, I understand...

My goal is to use phpunit only through Phive, removing it completely from composer.json: is this possible?

**Comment by theseer** [comment]
that's even the intention.

**Comment by Aerendir** [comment]
@theseer , ok, I need some guidance on how to do this: can you help me?

**Comment by MatthiasKuehneEllerhold** [comment]
Install
```bash
phive install phpunit
```
Use it:
```bash
tools/phpunit
# or
tools/phpunit.phar
```
