### ISSUE TITLE
--trust-gpg-keys not working?

### ISSUE THREAD

**Issue by neerolyte** [phar-io/phive#166]
I'm not sure if this isn't working or if I'm just miss reading the `--help` (are there more detailed docs anywhere else?).

`phive --help` seems to imply I can provide keys to be trusted if they're required during installation:

```
install [--target bin/] <alias|url> [<alias|url> ...]
[...]
        --trust-gpg-keys  Silently import these keys when required (multiple keys can be separated by comma)
```

but when I attempt to use the option I am still prompted to import the key:

```
[root@foo ~]# phive install --trust-gpg-keys 0x4AA394086372C20A phpunit
Phive 0.12.0 - Copyright (C) 2015-2018 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://phar.phpunit.de/phpunit-7.3.5.phar
Downloading https://phar.phpunit.de/phpunit-7.3.5.phar.asc
Downloading key 4AA394086372C20A
Trying hkps.pool.sks-keyservers.net (37.191.226.104)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x4AA394086372C20A&op=index&options=mr
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?search=0x4AA394086372C20A&op=get&options=mr
Successfully downloaded key

        Fingerprint: D840 6D0D 8294 7747 2937 7831 4AA3 9408 6372 C20A

        Sebastian Bergmann <sebastian@php.net> (2014-07-19)
        Sebastian Bergmann <sebastian@thephp.cc> (2014-07-19)
        Sebastian Bergmann <sebastian@phpunit.de> (2014-07-19)
        Sebastian Bergmann <sb@sebastian-bergmann.de> (2014-07-19)
        Sebastian Bergmann <sebastian.bergmann@thephp.cc> (2014-07-19)
        Sebastian Bergmann <sebastian.bergmann@bbp-consulting.com> (2017-01-10)

        Created: 2014-07-19

Import this key? [y|N] 
```

Is there some way to use `--trust-gpg-keys` or another alternative I've missed to achieve non-interactive installation from scratch (e.g in CI)?

**Comment by neerolyte** [comment]
Ok I figured out I need to specify the key without the `0x` prefix.

It would be good to have some basic docs somewhere with examples for things like this.

**Comment by theseer** [comment]
[Enhanced the documentation section](https://github.com/phar-io/phar.io/commit/ecabe0270f0ffffb9c5587f27f7a997ac8f1fd1a) on our website.
I might add a fallback to strip the "0x" from the key for an upcoming release so both variantes work.
