### ISSUE TITLE
Add support for custom repository list

### ISSUE THREAD

**Issue by belanur** [phar-io/phive#17]
It should be possible to add a custom repository list (e.g. ```~/.phive/repositories.local.xml```) with user-defined aliases and their respective repository URLs. 

The local repository list can NOT override entries from PHIVE's own repository list.

**Comment by theseer** [comment]
Despite the ticket text, in the current implementation the local repository list (~/.phive/local.xml) *can* overwrite PHIVE's aliases. This is intentional as we decided that this might be the better behavior.
