### ISSUE TITLE
tools dir is created even when not needed

### ISSUE THREAD

**Issue by jawira** [phar-io/phive#179]
I install all my phar files into `bin` directory:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phive xmlns="https://phar.io/phive">
  <phar name="phpstan" version="^0.11.2" installed="0.11.2" location="./bin/phpstan" copy="false"/>
  <phar name="phpab" version="^1.25.3" installed="1.25.3" location="./bin/phpab" copy="false"/>
</phive>
```

However every time I execute `$ phive install` an empty `tools` directory is created. 

Creating an empty directory is useless and I assume that's not the expected behavior.

Possible related issue #78

**Comment by jawira** [comment]
After diving into the code, it turns out that the correct way to define the install directory in `phive.xml` is using `<configuration>` tag:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phive xmlns="https://phar.io/phive">

  <configuration>
    <targetDirectory>bin</targetDirectory>
  </configuration>  

  <phar name="phpstan" version="^0.11.2" installed="0.11.2" location="./bin/phpstan" copy="false"/>
  <phar name="phpab" version="^1.25.3" installed="1.25.3" location="./bin/phpab" copy="false"/>
</phive>
```

Doing this way `tools` dir is not crated any more. 

I think having two ways of defining target dir is redundant (one on `xml`, the other on terminal `--target`). Also, is there a command to create this `<configuration>` tag or it should be done manually?

I really love Phive, but some things are pretty confusing and doc is hard to find.

**Comment by theseer** [comment]
Phive as of 0.14.0 should no longer create pointless directories.

If you find any remaining issues in this regard, please open a new ticket.
