### ISSUE TITLE
Multiple Signing Keys - Best Practice

### ISSUE THREAD

**Issue by amenk** [phar-io/phive#182]
So far I signed irobo (imi-digital/irobo) releases with my own key. In the future also one or more  colleagues will do releases.

What to do ? Shall we make a role account like opensource-signing@imi.de or does it help if I sign their keys and they will be automatically be accepted?

**Comment by theseer** [comment]
As you probably already know, `phive` requires the key associated with the signature provided. That key may of course change over time but, for probably obvious reasons, will require the user to accept this new key alongside a warning that the key used differs from one previously used.

It might be interesting for you to know that with issue #158 we plan to add trusted keys into the repositories.xml. While that still would prompt the user to import the key matching the signature, we could implement it in a way that multiple keys are allowed - without the aforementioned warning.

We did not implement and currently have no plans to add trust chains on top of that, so even if your key is trusted, it won't help to trust other keys. 


__Tl;Dr__: Creating a role account and "shared" signing key is - at least currently - recommended and what we do for phive and what for Fedora et al do as well for their distributions.

**Comment by mpdude** [comment]
Haven't tried it, but it might work if you setup a master key for the "role" and then distribute signing-only subkeys to everyone who might want to sign a release.

The master key can be kept mostly offline and is needed only to issue new subkeys or revoke existing ones.
