### ISSUE TITLE
Robust code

### ISSUE THREAD

**Issue by szepeviktor** [phar-io/phive#188]
PHPStan detects 60 occurrences of processing unexpected false/null values.

e.g.

```
 ------ --------------------------------------------------------------------------------------------------------
  Line   services/resolver/PharIoAliasResolver.php
 ------ --------------------------------------------------------------------------------------------------------
  42     Parameter #1 $name of class PharIo\FileSystem\Filename
         constructor expects string, string|false given.
 ------ --------------------------------------------------------------------------------------------------------
```

What is you opinion about it?

**Comment by szepeviktor** [comment]
all others are just 12

```
  Line   Factory.php                                                                                                                                          316    Parameter #1 $gpg of class PharIo\Phive\GnupgSignatureVerifier constructor expects Gnupg, Gnupg|PharIo\GnuPG\GnuPG given.
  348    Parameter #1 $gnupg of class PharIo\Phive\GnupgKeyImporter constructor expects Gnupg, Gnupg|PharIo\GnuPG\GnuPG given.

  Line   commands/remove/RemoveCommand.php
  46     Parameter #1 $filename of function unlink expects string, PharIo\FileSystem\Filename given.

  Line   commands/selfupdate/SelfupdateCommand.php
  101    Parameter #1 $source_file of function copy expects string, PharIo\FileSystem\Filename given.
  107    Parameter #1 $filename of function chmod expects string, PharIo\FileSystem\Filename given.
  113    Parameter #1 $filename of function unlink expects string, PharIo\FileSystem\Filename given.

  Line   commands/skel/SkelCommand.php
  22     Property PharIo\Phive\SkelCommand::$now (DateTime) does not accept DateTimeImmutable.

  Line   commands/update/UpdateCommandConfig.php
  62     Parameter #1 $uri of class PharIo\Phive\PharUrl constructor expects string, PharIo\Phive\PharUrl given.

  Line   shared/JsonData.php
  27     Property PharIo\Phive\JsonData::$parsed (stdClass) does not accept array|stdClass.

  Line   shared/PharRegistry.php
  112    Parameter #1 $pharNode of method PharIo\Phive\PharRegistry::nodetoPhar() expects DOMElement, DOMNode given.

  Line   shared/cli/Runner.php
  70     Parameter #1 $e of method PharIo\Phive\Cli\Runner::showException() expects Exception, PharIo\Phive\Exception&Throwable given.

  Line   shared/http/CurlHttpClient.php
  16     Class PharIo\Phive\ETag referenced with incorrect case: PharIo\Phive\Etag.
```

**Comment by theseer** [comment]
Thanks a lot for running PHPStan ;) Indeed we should add it to our tool chain.
And thanks for providing a bunch of PRs already!

Let me give some feedback on the things mentioned in this ticket:

```
  Line   services/resolver/PharIoAliasResolver.php
  42     Parameter #1 $name of class PharIo\FileSystem\Filename
         constructor expects string, string|false given.
```

I'm inclined to consider this a false positive. While technically correct, how could `\tempnam()` the way it's used ever return false?

---

```
   Line   Factory.php                                                                                                                                          
   316    Parameter #1 $gpg of class PharIo\Phive\GnupgSignatureVerifier constructor expects Gnupg, Gnupg|PharIo\GnuPG\GnuPG given.
   348    Parameter #1 $gnupg of class PharIo\Phive\GnupgKeyImporter constructor expects Gnupg, Gnupg|PharIo\GnuPG\GnuPG given.
```

These are false positives. `PharIo\GnuPG\GnuPG` is a surrogate in case `ext/gnupg` is not available and mapped via `class_alias` to `\Gnupg`.

---

```
>   Line   commands/selfupdate/SelfupdateCommand.php
>   101    Parameter #1 $source_file of function copy expects string, PharIo\FileSystem\Filename given.
>   107    Parameter #1 $filename of function chmod expects string, PharIo\FileSystem\Filename given.
>   113    Parameter #1 $filename of function unlink expects string, PharIo\FileSystem\Filename given.
>   Line   commands/update/UpdateCommandConfig.php
>   62     Parameter #1 $uri of class PharIo\Phive\PharUrl constructor expects string, PharIo\Phive\PharUrl given.
```

Obviously problematic. All related to __toString() not being applied in strict mode.
PHPStorm should actually have an inspection for that. I guess I'll open a bug ticket for that.
 
---

```
>   Line   shared/JsonData.php
>   27     Property PharIo\Phive\JsonData::$parsed (stdClass) does not accept array|stdClass.
```
See #193

---

```
>   Line   shared/PharRegistry.php
>   112    Parameter #1 $pharNode of method PharIo\Phive\PharRegistry::nodetoPhar() expects DOMElement, DOMNode given.
```
False positive. It's technically impossible to be anything but a \DomElement. Hence the `/** @var DOMElement $node */` in line 111.

---

``` 
>   Line   shared/cli/Runner.php
>   70     Parameter #1 $e of method PharIo\Phive\Cli\Runner::showException() expects Exception, PharIo\Phive\Exception&Throwable given.
> 
```
I don't understand this one. The private method `PharIo\Phive\Cli\Runner::showException()` has two usages, both pass in a custom Exception of ours in the catch block. One might argue about the beauty of it, but what am I missing to make that a problem?

**Comment by szepeviktor** [comment]
> I'm inclined to consider this a false positive. While technically correct, how could `\tempnam()` the way it's used ever return false?

When you use PHPStan you cannot be a businessman! When you use PHPStan you just fix all the errors -> you prosper for years :)

*in case you don't have write permission tempnam() will return false*

**Comment by szepeviktor** [comment]
I am not a developer at all, all I can do is distinguish between 0 and 1.
Actually I [prevent errors](https://www.szepe.net/), that is the one thing I do.

This issue is more about the first comment, the 60 unexpected values.

**Comment by theseer** [comment]
> > I'm inclined to consider this a false positive. While technically correct, how could `\tempnam()` the way it's used ever return false?
> 
> When you use PHPStan you cannot be a businessman! When you use PHPStan you just fix all the errors -> you prosper for years :)

Unless it aren't errors. 

> 
> _in case you don't have write permission tempnam() will return false_

No write permissions on `\sys_get_temp_dir()`? That's almost as unlikely as `new \DateTime('now');` throwing an exception - despite `\DateTime` would throw on broken input.

**Comment by szepeviktor** [comment]
> Unless it aren't errors.

I am no businessman, and this is my only focus, so here is how I do it:

- fix the error
- or contribute to PHPStan

That's it 😄

**Comment by szepeviktor** [comment]
okay, there is a third option: ignore the error in PHPStan's config file

**Comment by szepeviktor** [comment]
> That's almost as unlikely

See the issue's title: Robust code === prepare for edge cases

**Comment by theseer** [comment]
I do agree that edge cases, in general, should be handled. 
Some errors are so unlikely, that, imho, handling them makes the code harder to read than ignoring them.

Example: Running PHPStan with level `max` spits out quite a few edge case warnings that cannot practically occur. `preg_replace` for instance will return false on errors. Does that mean we'd have to wrap every preg_replace call into an if statement? That'll be an edge case handling for a case that can hardly happen, is pretty much impossible to test for, makes the code harder to read and slower since it's testing for something that won't (ever) happen.

I do appreciate the effort made but some of the errors you/PHPStan report are simply no errors - imho.

The php core function `sys_get_temp_dir()` is bound to return a string, pointing to an existing directory. It's very unlikely the current application has no write permissions to it. And `tempnam()` would replace a broken path to whatever is the system temp directory. It would trigger a notice, which we translate into an exception. Again, case handled => False positive of an edge case that would be handled anyway.

**Comment by szepeviktor** [comment]
I do understand want you mean.

> a few edge case warnings that cannot practically occur

My only service to my clients is to prevent errors **for several years**, so if you don't want to meet these *hiding errors* you correct them ASAP. I stress: I write no code! :)

**Comment by szepeviktor** [comment]
You must know all these!! You are a The Seer.

**Comment by theseer** [comment]
Srsly?

**Comment by szepeviktor** [comment]
```
viktor@mail:~$ TMPDIR=/root php -r "var_dump(tempnam('tempy', 'xx'));"
PHP Notice:  tempnam(): file created in the system's temporary directory in Command line code on line 1
bool(false)
```

**Comment by theseer** [comment]
Sure, but you do realize that the notice will be turned into an exception within `phive` even before a potential return value could be false, right?

**Comment by szepeviktor** [comment]
Okay. I give in.

I send you a PR instead.

ps. what turns a notice into an exception?

**Comment by theseer** [comment]
https://github.com/phar-io/phive/blob/d77505cc9618027141a8d8f7a6461e5399f814cf/src/shared/cli/Runner.php#L143  

and 

https://github.com/phar-io/phive/blob/d77505cc9618027141a8d8f7a6461e5399f814cf/src/shared/cli/Runner.php#L88

respectively.

:-)

**Comment by szepeviktor** [comment]
Thanks.

**Comment by szepeviktor** [comment]
PHPStan could prevent https://github.com/phar-io/phive/issues/180
