### ISSUE TITLE
unlink() receives an object in RemoveCommand

### ISSUE THREAD

**Issue by szepeviktor** [phar-io/phive#190]
This class has strict_types so:

`Fatal error: Uncaught TypeError: unlink() expects parameter 1 to be a valid path, object given`

**Comment by ondrejmirtes** [comment]
It would probably be beneficial for this repository to adopt static analysis that would find this error :)

**Comment by szepeviktor** [comment]
Yes https://github.com/phar-io/phive/issues/188
