### ISSUE TITLE
GitHub rate limiting stops Travis tests

### ISSUE THREAD

**Issue by szepeviktor** [phar-io/phive#197]
We get HTTP/403 for phpstan's releases.

**Comment by theseer** [comment]
Interesting, since the github api token should be set in `.travis.yml`.

**Comment by szepeviktor** [comment]
https://travis-ci.org/phar-io/phive/jobs/520744156

**Comment by theseer** [comment]
I can read, you know?

**Comment by szepeviktor** [comment]
No offense. I've put this link here as a reference.

**Comment by szepeviktor** [comment]
I see: we have a GitHub token.
