### ISSUE TITLE
Phpstan key produces errors.

### ISSUE THREAD

**Issue by lippok** [phar-io/phive#206]
On my CI the installation of phpstan fails currently. The key server keys.fedoraproject.org seems to be down and phive is falling back to keyserver.ubuntu.com. This works fine for php-cs-fixer but the import of the key for phpstan (8E730BA25823D8B5) fails:

> Trying to connect to keyserver.ubuntu.com (162.213.33.8)
> Downloading https://keyserver.ubuntu.com/pks/lookup?search=0x8E730BA25823D8B5&op=index&options=mr
> Trying to connect to keyserver.ubuntu.com (162.213.33.8)
> Downloading https://keyserver.ubuntu.com/pks/lookup?search=0x8E730BA25823D8B5&op=get&options=mr
> Successfully downloaded key
> [ERROR]   Failed to parse provided key info: info:1:1
> [ERROR]   pub:8E730BA25823D8B5:1:2048:1502824304::
> [ERROR]   

I'm wondering if this is an error within phive, because I can import the key manually:
> gpg --keyserver keyserver.ubuntu.com --recv-keys 8E730BA25823D8B5

**Comment by theseer** [comment]
Fixed in 0.13.0.
