### ISSUE TITLE
Parsing key data failed with error code 2: unlink

### ISSUE THREAD

**Issue by ktomk** [phar-io/phive#208]
I ran into a problem installing with phive and key verification:

~~~
...
Successfully downloaded key.
[WARNING]  Parsing key data failed with error code 2: unlink(/home/travis/.phive/_tmp_wrk/pubring.kbx): No such file or directory 
~~~

The issue is that after successfully downloading the key from the key server, it's not found any longer.

Then phive tries the next key server (despite network was OK previously), with success again, but then can't find the key on the system any longer.

Then a thrid trip to another key server, again success network operation with the keyserver and again failure on the local system.

Here the program output:

~~~
$ ./bin/phive install --trust-gpg-keys D2CCAC42F6295E7D,8E730BA25823D8B5
Phive 0.13.0 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/maglnet/ComposerRequireChecker/releases
Downloading https://github.com/maglnet/ComposerRequireChecker/releases/download/2.0.0/composer-require-checker.phar
Downloading https://github.com/maglnet/ComposerRequireChecker/releases/download/2.0.0/composer-require-checker.phar.asc
Downloading key D2CCAC42F6295E7D
Trying to connect to keys.openpgp.org (37.218.245.50)
Downloading https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0xD2CCAC42F6295E7D
Successfully downloaded key.
[WARNING]  Parsing key data failed with error code 2: unlink(/home/travis/.phive/_tmp_wrk/pubring.kbx): No such file or directory 
Trying to connect to keys.fedoraproject.org (140.211.169.207)
Downloading https://keys.fedoraproject.org/pks/lookup?op=get&options=mr&search=0xD2CCAC42F6295E7D
Successfully downloaded key.
[WARNING]  Parsing key data failed with error code 2: unlink(/home/travis/.phive/_tmp_wrk/pubring.kbx): No such file or directory 
Trying to connect to keyserver.ubuntu.com (162.213.33.9)
Successfully downloaded key.
[WARNING]  Parsing key data failed with error code 2: unlink(/home/travis/.phive/_tmp_wrk/pubring.kbx): No such file or directory 
Trying to connect to hkps.pool.sks-keyservers.net (37.191.231.105)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?op=get&options=mr&search=0xD2CCAC42F6295E7D
Successfully downloaded key.
[WARNING]  Parsing key data failed with error code 2: unlink(/home/travis/.phive/_tmp_wrk/pubring.kbx): No such file or directory 
[ERROR]    PublicKey D2CCAC42F6295E7D not found on key servers 
~~~

The phive.xml is:
~~~
<?xml version="1.0" encoding="UTF-8"?>
<phive xmlns="https://phar.io/phive">
  <phar name="composer-require-checker" version="^2.0" installed="2.0.0" location="./tools/composer-require-checker" copy="false"/>
  <phar name="phpstan" version="^0.11.15" installed="0.11.15" location="./tools/phpstan" copy="false"/>
</phive>
~~~

This is a run from Travis, find the job here: https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/595828727 (scroll to end).

**Comment by theseer** [comment]
I'll try to have a in-depth look asap. So far, I have no idea why that would happen.

**Comment by ktomk** [comment]
@theseer: If it helps, I triggered another Travis build this time w/

* output GPG version: https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/596779039#L530
* strace

**Comment by theseer** [comment]
Ah!

That system still uses GPG 1.x, the "missing" file is generated by GPG 2.x.

I'll update phive to handle 1.x and 2.x GPG releases and cleanup properly for both versions. Sorry about that.

**Comment by theseer** [comment]
Need to run some more tests tomorrow but I'm quite sure this fixes it.

**Comment by ktomk** [comment]
@theseer Is there a way I install phive to the patch version? Then I can just run it in the same scenario on Travis.

**Comment by theseer** [comment]
We probably should start providing nightly builds ;)

Other than that: `ant phar` will generate a phar archive. You could provide a download path for it or add it to the repository?

**Comment by ktomk** [comment]
I could put it to a run. It now looks different but still fails:

https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/597069462#L704

~~~
Trying to connect to hkps.pool.sks-keyservers.net (192.146.137.98)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?op=get&options=mr&search=0x8E730BA25823D8B5
Successfully downloaded key.
[WARNING]  Parsing key data failed with error code 0: No UIDs in key found 
[ERROR]    PublicKey 8E730BA25823D8B5 not found on key servers 
~~~

**Comment by theseer** [comment]
*sigh*

Of course the GPG 1.x output format is totally different...

**Comment by ktomk** [comment]
if there is anything I should run verbatim on that system so that the output becomes more obvious, just let me know.

**Comment by theseer** [comment]
Btw: 
> pub   rsa2048 2017-08-15 [SC] [expired: __2019-08-15__]

**Comment by theseer** [comment]
Thanks, nothing you need to do atm.
The GnuPG 1.x output seems to be quite different from the 2.x version, so I have to write a 2nd parser for old systems that only have 1.x installed.

**Comment by ktomk** [comment]
is there a test for gpg2 as utility name? older systems can have gpg 1 and 2 and the second one as gpg2.

Like on travis, just added a version check `gpg2 --version`: https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/597077537#L529

**Comment by theseer** [comment]
The last GnuPG 1.x release is version 1.4 from 2018. While that of course is some time ago and may be considered deprecated, it's not long enough yet to simply not support it.

So while we might very well check for `gpg2`, we still need to have a fallback for the outdated version.

Or?

**Comment by ktomk** [comment]
Honestly, I would write the GPG 1 parser when required. It's good to understand what is going on first of all, and checking for gpg2 looks quite fine to me, but I don't know the phive internals. I know that gpg2 is available since longer on such kind of configured systems so would right now say, it's fine and not discriminate against older systems much.

Tom would perhaps even start w/ an environment parameter:

~~~
$ PHIVE_GPG=gpg2 phive install ....
~~~

If that works Tom would figure out if an automatic detection is feasible. Tom guesses it's easy, so after confirming it work, Tom would add controlling cli options so that the behaviour can be controlled:

~~~
usage: phive [--gpg-detect=<mode>]

    --gpg-detect=<mode>    mode to detect preferred GPG utility name
                                   gpp:  standard way
                                   gpg2: try first gpg2, then gpg
~~~

Something along these lines.

Then I would perhaps put the GPG 1 parser more to the top of the TODO / nice-to-have list and ensure the build system is able to test against a plethora of different GPG versions and environments (starting with two maybe). the output from these versions can be used as fixture for a parser, which then can be TDD'ed. all just on a feature branch so when the times come that GPG 1 support is required, the project is prepared.

Then create an order of parsers, and the first parser which can parse wins.

Until then if you prefer to give a gpg 1 parser a try directly, it's easy to run it on the travis build of the PHP_CS_Fixer project.

**Comment by feryardiant** [comment]
Come across similar issue on Windows 

```
> phive install wp
Phive 0.13.0 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/wp-cli/wp-cli/releases
Downloading https://github.com/wp-cli/wp-cli/releases/download/v2.3.0/wp-cli-2.3.0.phar
Downloading https://github.com/wp-cli/wp-cli/releases/download/v2.3.0/wp-cli-2.3.0.phar.asc
Downloading key A3A2E8F226F0BC06
Trying to connect to keys.openpgp.org (37.218.245.50)
Downloading https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0xA3A2E8F226F0BC06
Successfully downloaded key.
[WARNING] Parsing key data failed with error code 0: No UIDs in key found
Trying to connect to keys.fedoraproject.org (140.211.169.207)
Downloading https://keys.fedoraproject.org/pks/lookup?op=get&options=mr&search=0xA3A2E8F226F0BC06
Successfully downloaded key.
[WARNING] Parsing key data failed with error code 2: unlink(C:\Users\fery\.phive\_tmp_wrk\pubring.kbx~): No such file or directory
Trying to connect to keyserver.ubuntu.com (162.213.33.9)
Downloading https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0xA3A2E8F226F0BC06
Successfully downloaded key.
[WARNING] Parsing key data failed with error code 2: unlink(C:\Users\fery\.phive\_tmp_wrk\pubring.kbx~): No such file or directory
Trying to connect to hkps.pool.sks-keyservers.net (37.191.231.105)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?op=get&options=mr&search=0xA3A2E8F226F0BC06
Successfully downloaded key.
[WARNING] Parsing key data failed with error code 2: unlink(C:\Users\fery\.phive\_tmp_wrk\pubring.kbx~): No such file or directory
[ERROR]   PublicKey A3A2E8F226F0BC06 not found on key servers
```

... but not in Ubuntu WSL

```
$ phive install wp
Phive 0.13.0 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/repos/wp-cli/wp-cli/releases
Downloading https://github.com/wp-cli/wp-cli/releases/download/v2.3.0/wp-cli-2.3.0.phar
Downloading https://github.com/wp-cli/wp-cli/releases/download/v2.3.0/wp-cli-2.3.0.phar.asc
Downloading key A3A2E8F226F0BC06
Trying to connect to keys.openpgp.org (37.218.245.50)
Downloading https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0xA3A2E8F226F0BC06
Successfully downloaded key.
[WARNING]  Parsing key data failed with error code 0: No UIDs in key found
Trying to connect to keys.fedoraproject.org (140.211.169.207)
Downloading https://keys.fedoraproject.org/pks/lookup?op=get&options=mr&search=0xA3A2E8F226F0BC06
Successfully downloaded key.

        Fingerprint: 63AF 7AA1 5067 C056 16FD DD88 A3A2 E8F2 26F0 BC06

        WP-CLI Releases <releases@wp-cli.org>

        Created: 2018-05-31

Import this key? [y|N] y
Linking /home/fery/.phive/phars/wp-2.3.0.phar to /home/fery/.local/share/tools/wp-cli
```

Both runs similar version of GPG

```
# Ubuntu 18.04 WSL
gpg (GnuPG) 2.2.4
libgcrypt 1.8.1
Home: /home/fery/.gnupg

# Windows 10 Home 1909
gpg (GnuPG) 2.2.16
libgcrypt 1.8.4
Home: C:\Users\fery\AppData\Roaming\gnupg
```

**Comment by jawira** [comment]
For people having this issue with Travis, I fixed it doing this:

```yaml
before_install:
  - '### Using GPG2 ###'
  - sudo mv /usr/bin/gpg /usr/bin/gpg1
  - sudo update-alternatives --verbose --install /usr/bin/gpg gnupg /usr/bin/gpg2 50
  - sudo apt-get -y install dirmngr --install-recommends
```

Source: https://makandracards.com/aslamk/28305-how-to-change-the-default-gnupg-version-from-gpg-to-gpg2

**Comment by steffenbrand** [comment]
I'm running into the same error:

```
gpg (GnuPG) 2.0.22
libgcrypt 1.5.3
```

```
Phive 0.13.0 - Copyright (C) 2015-2019 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://squizlabs.github.io/PHP_CodeSniffer/phars/phpcs-3.5.2.phar
Downloading https://squizlabs.github.io/PHP_CodeSniffer/phars/phpcs-3.5.2.phar.asc
Downloading key 31C7E470E2138192
Trying to connect to keys.openpgp.org (37.218.245.50)
Downloading https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0x31C7E470E2138192
Successfully downloaded key.
[WARNING]  Parsing key data failed with error code 2: unlink(/home/vagrant/.phive/_tmp_wrk/pubring.kbx): No such file or directory 
Trying to connect to keys.fedoraproject.org (140.211.169.207)
Downloading https://keys.fedoraproject.org/pks/lookup?op=get&options=mr&search=0x31C7E470E2138192
Successfully downloaded key.
[WARNING]  Parsing key data failed with error code 2: unlink(/home/vagrant/.phive/_tmp_wrk/pubring.kbx): No such file or directory 
Trying to connect to keyserver.ubuntu.com (162.213.33.9)
Successfully downloaded key.
[WARNING]  Parsing key data failed with error code 2: unlink(/home/vagrant/.phive/_tmp_wrk/pubring.kbx): No such file or directory 
Trying to connect to hkps.pool.sks-keyservers.net (192.146.137.99)
Downloading https://hkps.pool.sks-keyservers.net/pks/lookup?op=get&options=mr&search=0x31C7E470E2138192
Successfully downloaded key.
[WARNING]  Parsing key data failed with error code 2: unlink(/home/vagrant/.phive/_tmp_wrk/pubring.kbx): No such file or directory 
[ERROR]    PublicKey 31C7E470E2138192 not found on key servers
```
Could I provide any more infos that might help you fix the issue?

**Comment by griesi007** [comment]
I am also facing this error:

gpg (GnuPG) 2.2.11
libgcrypt 1.8.4

**Comment by theseer** [comment]
@ktomk Why would gpg2 need access to keyservers? Phive should handle all the search and downloading. The gpg(2) binary is only used to do import the public key into the keyring, show details and of course verify signatures.

**Comment by griesi007** [comment]
@theseer I was using the latest release 0.13.0 . Had no time yet for a custom build

**Comment by theseer** [comment]
The aforementioned commit should fix the problem of missing files for GPG 1.x - but is incomplete, as 1.x requires a different parser.

I'm confused as to why a 2.x file is causing issues for you but given the logic changed, that particular problem should not occur again either way.

**Comment by ktomk** [comment]
> @ktomk Why would gpg2 need access to keyservers? Phive should handle all the search and downloading. The gpg(2) binary is only used to do import the public key into the keyring, show details and of course verify signatures.

IIRC this is specific to the dev-tools install on Travis in the PHP_CSFixer. For the installation of Phive itself this is needed as keys are imported from keyservers ([ref](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.15/dev-tools/install.sh#L40)). As for the workaround it was switched from default GPG1 to GPG2, this needed a keyserver for transparent use.

Will try a build later w/ the fix-version and post results then.

**Comment by ktomk** [comment]
@theseer As you wrote, now parsing fails (but no error on the unlink any longer): [Output start in a Travis build](https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/604042160#L528),

**Comment by steffenbrand** [comment]
@theseer The fix in https://github.com/phar-io/phive/commit/3d288ed748c1b54652826dc05a918649b1a489bf works perfectly fine for me.
Would be nice if you could tag a 0.13.1 :-)

**Comment by theseer** [comment]
I'm working on getting version 1 output parsed right now. Will release asap.
I don't like having a half-working fix ;)

**Comment by theseer** [comment]
Turns out, with `--fixed-list-mode` even GPG 1.x generates "proper" output compatible enough with the 2.x output that the parser works just fine.

After various tests on my local system did not show any problems neither 1.x nor 2.x, I made a new release.

please give it a try!

If the problem persists, please open a *new* issue as i consider the core problem of this issue fixed.

**Comment by ktomk** [comment]
Just fired a new travis build that downloaded Phive 0.13.1 and used it then.

It's working.

But you might want to check the output as it looks like some var_dumps() are in there to review the GPG commands:

https://travis-ci.org/FriendsOfPHP/PHP-CS-Fixer/jobs/604713077#L527

**Comment by theseer** [comment]
Duh.

**Comment by griesi007** [comment]
Works for me also. Thanks!

**Comment by steffenbrand** [comment]
Works fine, thanks a lot!

**Comment by ktomk** [comment]
@theseer Thanks for the quick turnaround time.

**Comment by theseer** [comment]
Thanks, but to be honest I'm not happy that a) the problem even arose and b) it still took quite many days and various helping hands to get resolved. So thanks for your input and support as well!

**Comment by ktomk** [comment]
Yes, I would also wish to not run into this firsthand. But I have to thank you first of all again. For sure.

So maybe for the bigger picture let me tell you a story. There is this fine IDE called PhpStorm, if you don't use ist, it's an IDE for PHP. Anyway, it's not the IDE I'd like to highlight, but an extension of a very fine person named Vladimir Reznichenko who wrote a plugin to that IDE called *Php Inspections ​(EA Extended)*. It helps writing or reviewing PHP code by giving hints (and fixes) directly inside the code editor.So as being a Phpstorm user myself and writing PHP and sort of use it all day.

This fine plugin ships with many, many inspections but one that I'd like to highlight is about creating directories (in PHP that is the `mkdir()`  function as you absolutely know I'm sure) . And the inspection is about *not* handling race conditions. The moment a script creates a directory as it needs it, creating the directory might fail because it already has been created. So the fix suggestion is in case `mkdir` fails (and only then), to add an additional check if the directory already exists *now* to *not* throw an exception (or do some other kind of error handling).

Even thought the problem here is not about creating something but destroying something and therefore a race-condition is much less likely, this inspection reminds me on idempotent operations on the file-system. For example when I write myself nowadays a utility function to delete a file, on failure I check if the file is gone (or similar). Because when the main routine commands to delete a file and the file is deleted (regardless of whether it existed or not), then the operation is clean / fine.

If I have such expectations from the beginning this is totally straight forward. However if I would have encoded a library first that throws on every "unexpected" situations, it's not so straight forward any longer. Does the consumer of the easy exception throwing library expects such exceptions and branches based on them? this question can't be answered any longer precisely as one would need to guess as any consumer could do all possible things incl. branch based on exceptions uses as "return values".

For utilities that run in the shell my learning over the years was that idempotent operation is very straight forward and allows to keep complexity low. This reminds me on this nice article on writing idempotent shell scripts which boils down (as far as I remember) to use `mkdir -p` instead of just  `mkdir` or `rm -f` instead of just `rm`. Point in case is, when the system is involved you're more concerned about the state to achieve and not so much about the state that is.

Your fix handles this by only delete if the file exists. The besaid IDE plugin if it would be perfect might highlight a race-condition there (I'm sure it does not cover it, but I would be pleasantly surprised to be proven wrong), as the file might have been deleted despite the existence check earlier.

In the case of Phive, it's the question what the underlying filename API wants to deliver. Maybe similar to just a delete method (as the `rm` w/o flags), a user of that library might as for a `rm -f`  variant of the  delete method as it's more about the delete than the "correct" parameter being a file to delete.

But I am no good person to judge here. This is just what I considered to response after a couple of days as I think honestly your open thoughts demand a response and I also feel with you and can perfectly understand your criticism but I also know that these integration issues are most often the hardest to deal with.

And I really think that the way you handled this issue is really great. You were very responsive, you kept this up-to-date, you provided development builds (at least very good and easy instructions building myself) and for the minor things you fixed just literally after comment. Really no complaints at all here. I also find three weeks for an upstream fix of something that comes unexpected and is not just a single byte exchange in code a very fast resolution time. And the only problem I could spot on the beginning was, that a parser error on some different layer became visible with a file-system error. So it was not clear to me from the beginning this was a parser error (it was one, right?).

**Comment by theseer** [comment]
Thanks for the long reply.

I use PHPStorm as well as EA Inspections Ultimate. Neither is helping in this case as the problem was *not* a race condition. While I do see that potentially the file might not have been created to begin with because something went wrong, the actual problem here was that depending on the version of Gnupg in use, the files created are different.

I personally dislike code deleting with wildcards so I deliberately choose to explicitly delete the files created. My mistake was not to have considered GnuPG 1.x and the different sets of files as well as the different output format.

So technically, this were indeed two (independent) problems.

But thanks again for the praise :)

**Comment by ktomk** [comment]
The praise was only for the story. I really do appreciate the strictness you adhere to. And as I wrote I'm not judging here simply because you need to do all these kind of (underlying) decisions. And as I can read there is little fear I do need to have about this.

Thanks again.
