### ISSUE TITLE
Improve CI-pipeline

### ISSUE THREAD

**Issue by jaapio** [phar-io/phive#212]
Currently, this repository has configs setup for `phpstan` and `php-cs-fixer`, but both are not executed in the `ant` setup nor in the travis config.

I would like to set up a number of github actions to execute them. What we could in those actions:

- composer install
- phive install
- run phpstan
- run php-cs-fixer

If you like the idea, please sign up for github actions beta, and notify me in this issue. I will create a pr to get you started. 

The alternative is to execute all this in travis, that way it would take longer to get the build results but we will be sure that the fixed levels are covered in each PR

**Comment by theseer** [comment]
I very much like the idea, though I'm considering the remove phpstan again and replace it with psalm as I consider it the better tool for the job with a less annoying config file format ;)

**Comment by theseer** [comment]
`You now have access to GitHub Actions!`

**Comment by jaapio** [comment]
phpstan and psalm are discovering different issues, many projects nowadays are using them both. But I do agree that the config format of phpstan is not exactly what we want to have :-)

**Comment by jaapio** [comment]
closing this one in favor of #213 and #216 
Thanks for your help so far, let's discuss the details in the PR's
