### ISSUE TITLE
Hard dependency on `which` command

### ISSUE THREAD

**Issue by rask** [phar-io/phive#217]
Currently the application (on Unixy platforms) expects the `which` command to be available at all times. Sometimes it is not available, and Phive becomes ununsable on those systems. For instance there are lean Docker containers that do not come with `which` installed.

Could the implementation be adjusted so systems can provide some other mechanism to validate existence of binaries?

**Comment by theseer** [comment]
Probably. Any suggestions?

**Comment by rask** [comment]
I was thinking that using either `type <bin>` or `command -v <bin>` would be more universal, if we want a quick win regarding this. My initial check says that these work with just `/bin/sh`.

Another option would be to allow the user to pass in args such as

    phive install --bincheck-command type --bincheck-expect 0

where command is the shell command to run and expect is the expected exit code or output or similar. But this would probably add too much complexity to make it feasible.
