### ISSUE TITLE
phive outdated: How to know when packages needs to be updated?

### ISSUE THREAD

**Issue by Aerendir** [phar-io/phive#223]
I use Phive to install, among the others, Phan, PHPStan and Psalm.

I'm used to use fixed versions for them as, on update they may rise new issues and also a simple change in the code causes a lot of time required to get a green build.

So I prefer to have aoutdated versions and then, when I have the time, update the versions and get a green build with the latest versions.

Now, my question is: as I use fixed versions, how can I know i the packages I'm using are up to date or not?

Before using Phive, I was used to run `composer outdated` to know if there are any packages that need to be updated.

But now, with Phive, what can I run?

**Comment by theseer** [comment]
We indeed are lacking an "outdated" command.

I'll see if i can actually implement that on my way home later. No promises though.

**Comment by theseer** [comment]
Okay, we now do have an `outdated` command. It's still a bit rough as I think we should support a few options here that for now I hardcoded (like having support for --prefer-offline) or an machine readable output.

This is not yet released. If you want to try it, you have to use the current master.

**Comment by Aerendir** [comment]
@theseer , thank you very very much! Tomorrow I will give it a try!
