### ISSUE TITLE
[Bug] rtrim() expects parameter 1 to be string, bool given

### ISSUE THREAD

**Issue by Aerendir** [phar-io/phive#224]
Th complete error is this:

          An error occurred while processing your request:

          rtrim() expects parameter 1 to be string, bool given
          
          #0 src/shared/cli/input/ConsoleInput.php(23)
          #1 src/shared/cli/input/ConsoleInput.php(23): rtrim()
          #2 src/services/key/KeyService.php(64): PharIo\Phive\Cli\ConsoleInput->confirm()
          #3 src/services/key/KeyService.php(48): PharIo\Phive\KeyService->allowedToImport()
          #4 src/services/signature/gpg/GnupgSignatureVerifier.php(27): PharIo\Phive\KeyService->importKey()
          #5 src/services/phar/PharDownloader.php(84): PharIo\Phive\GnupgSignatureVerifier->verify()
          #6 src/services/phar/PharDownloader.php(44): PharIo\Phive\PharDownloader->verifySignature()
          #7 src/services/phar/PharService.php(22): PharIo\Phive\PharDownloader->download()
          #8 src/services/phar/InstallService.php(45): PharIo\Phive\PharService->getPharFromRelease()
          #9 src/commands/install/InstallCommand.php(45): PharIo\Phive\InstallService->execute()
          #10 src/commands/install/InstallCommand.php(37): PharIo\Phive\InstallCommand->installRequestedPhar()
          #11 src/shared/cli/Runner.php(193): PharIo\Phive\InstallCommand->execute()
          #12 src/shared/cli/Runner.php(60): PharIo\Phive\Cli\Runner->execute()
          #13 (313): PharIo\Phive\Cli\Runner->run()
          #14 {main}

          Environment: PHP 7.4.1
          Phive Version: 0.13.2

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!

You can see the context here: https://github.com/Aerendir/PHPValueObjects/commit/000b01272f09050d410e429b583029ce4c4384bc/checks?check_suite_id=406270535#step:5:308

**Comment by theseer** [comment]
Okay, looking at the output, that's a few problems in one ;)

First we obviously fail to detect that we don't have an interactive shell on github actions (1) and thus show the progress bar when downloading and also try to get confirmation to import the gpg key. Since phive fails to open a stream to read from, the following process step doesn't deal with the failed attempt properly (2), leading to the actual error you saw.

But even if those issues weren't there, it still wouldn't work: Since there is no way to confirm the import interactively, the install would have still failed.
Unless previously imported into phive's gpg keyring, you'd have to supply a list of trusted keys to the phive command. That should actually mitigate the problem as no interaction is required and the bug won't be triggered.

**Comment by Aerendir** [comment]
Ok, I'm understanding the problem...

Can you, please, give an example of the command that I should run?

**Comment by theseer** [comment]
Sure: `phive install --no-progress --trust-gpg-keys {keyid-without-0x},{other-keyid-without-0x},...`

The `--no-progress` will avoid the clutter until we fix the detection code ;)

**Comment by theseer** [comment]
Alternatively, you can of course just import the proper keys into the gpg keyring using gpg's cli idependentely. If you make the CI keep the keyring, that's then a one time action ;)

**Comment by Aerendir** [comment]
@theseer , I'm using Github Actions: I don't know if I can keep the keyring... I will look deeper in this tomorrow...

**Comment by Aerendir** [comment]
@theseer and thanks for the command example!

**Comment by Aerendir** [comment]
@theseer , using `--no-progress` causes an error:

> [ERROR]    Error while processing arguments to command 'install': 
> [ERROR]    Unknown option: no-progress 

You can see it here: https://github.com/Aerendir/PHPValueObjects/runs/403694388#step:5:8

**Comment by theseer** [comment]
Oops, used the wrong order:

`phive --no-progress install  --trust-gpg-keys {keyid-without-0x},{other-keyid-without-0x},...`

The `--no-progress` is a global option, not a command parameter.

**Comment by Aerendir** [comment]
Ok, I'm going to try the new order...

Is there a way to know beforehand which is the keyid of a package? Currently I'm going to run the CI for many times and adding the keys one by one but it is a very time intensive task 😅

**Comment by Aerendir** [comment]
The new order of the options works perfectly 🎉

**Comment by theseer** [comment]
> Is there a way to know beforehand which is the keyid of a package?

If you installed things locally, `phive status` should show you all installed phars with their keyid - if any.

**Comment by theseer** [comment]
Duplicate for #218
