### ISSUE TITLE
Are there stats for phive downloads?

### ISSUE THREAD

**Issue by szepeviktor** [phar-io/phive#234]
I mean download count for tools not phive itself.

**Comment by theseer** [comment]
TL;DR: No.

Longer answer:

At phar.io we do not host any phars, not even phive itself (the download link is a redirect to our github.com releases). The only thing we host ourselves is the repository meta data. We do have a dedicated logfile for pure statistical reasons, storing time of request, phive version, php version and os.

I wouldn't know how to collect installs, unless we explicitly add some sort of tracking code to phive. Which I don't consider a good idea - at all.

**Comment by szepeviktor** [comment]
Thank you.
