### ISSUE TITLE
Temporary option not used

### ISSUE THREAD

**Issue by MacFJA** [phar-io/phive#236]
Since the version [0.7.0](https://github.com/phar-io/phive/blob/master/CHANGELOG.md#070---2017-05-19), the option `--temporary` of the `install` command don't do anything.

The method `PharIo\Phive\InstallCommandConfig::doNotAddToPhiveXml()` is not call anywhere (except for unit tests).
[The condition that prevent `phive.xml` to be update](https://github.com/phar-io/phive/compare/0.6.3...0.7.0#diff-3640243449a8877a7212df035c2c34eeL59-L62) was not reused in the `InstallService`.

Should this option be removed or reimplemented ?

**Comment by theseer** [comment]
This is certainly a bug. And one we should have found ourselves.

I think it's a good option to have and thus should stay.
