### ISSUE TITLE
make stable release

### ISSUE THREAD

**Issue by glensc** [phar-io/phive#241]
I'd love to get `phive` installed with brew, but
brew rejects pre-release packages being added to their repository:
- https://github.com/Homebrew/homebrew-core/pull/39469#issuecomment-504403221

any chance to get a stable release here?

**Comment by theseer** [comment]
Yes and no.

I'd love to make a stable release but there are some refactoring tickets pending that might lead to BC breaks and we have a few missing features. I'm not convinced we're ready for 1.0 yet.

With the upcoming 0.14.0 we're getting a lot closer to that though.

**Comment by glensc** [comment]
Perhaps the confusion is about pre-release vs stable API.

If you publish your releases as not pre-release, but standard GitHub release (untick the pre-release checkbox). the pre-releases are intended for 0.1.2rc1, prior actual 0.1.2 release. that has nothing to do with API stability.

i.e, it doesn't have to be 1.0 release.

**Comment by theseer** [comment]
I guess we can do that :)

**Comment by theseer** [comment]
Phive 0.14.0 has just been released.
