### ISSUE TITLE
Error on phar.io release link

### ISSUE THREAD

**Issue by shivammathur** [phar-io/phive#242]
Please fix this link. There is an issue with the SSL certificate.
https://phar.io/releases/phive.phar

**Comment by theseer** [comment]
Not on our side:

- https://sslping.com/phar.io  
- https://observatory.mozilla.org/analyze/phar.io

Looks all good. Otherwise it should redirect to github.com. If there's a TLS issue, I can't do much about it...

**Comment by shivammathur** [comment]
This was the error, it redirects to GitHub releases now.
```bash
> wget https://phar.io/releases/phive.phar
Resolving phar.io... 188.94.27.6
Connecting to phar.io|188.94.27.6|:443... connected.
ERROR: cannot verify phar.io's certificate, issued by `/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3':
  Unable to locally verify the issuer's authority.
ERROR: certificate common name `netpirates.net' doesn't match requested host name `phar.io'.
To connect to phar.io insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.
```

**Comment by theseer** [comment]
I have literally no idea how your `wget` managed to get into that state. The only way to get a `netpirates.net` host is by not using SNI when connecting. I did *not* change anything on the server except for the php code finding the proper redirect. So if there apparently was some sort of TLS issue, it must have been a problem on either your end or at Let's Encrypt. Either way, seems working again so probably no point in debugging this further.
