### ISSUE TITLE
Releases URL no longer working?

### ISSUE THREAD

**Issue by burzum** [phar-io/phive#243]
According to the website https://phar.io/ you can get the archive doing this:

> wget -O phive.phar https://phar.io/releases/phive.phar

But `https://phar.io/releases/phive.phar` is giving me a 404 and when I try it in Chrome it shows:

```
This site can’t be reachedThe webpage at https://phar.io/releases/phive.phar might be temporarily down or it may have moved permanently to a new web address.
ERR_HTTP2_PROTOCOL_ERROR
```

We have some automated scripts that access this file when running tests for example so this is causing us some trouble right now.

**Comment by theseer** [comment]
Duplicate of #242 

Should work again.
