### ISSUE TITLE
Installing deployer with phive produces an error

### ISSUE THREAD

**Issue by Lapsus** [phar-io/phive#256]
As far as i understand the following should work, right? but it does not.

```
$ phive install https://github.com/deployphp/distribution/releases/tag/v6.8.0

Phive 0.13.2 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]    Could not extract PHAR version from https://github.com/deployphp/distribution/releases/tag/v6.8.0
```

I am not shure if it is a problem with their phar file causing the problem or what needs to be done to make it work.

**Comment by theseer** [comment]
No, it shouldn't work. At least not in this case.
Unfortunately, the error message is, while technically correct, rather confusing.

You are trying to install by providing a full https-url. While `phive` does support installing this way, the URL is expected to point to an actual phar archive, not just some html document at github. For https-urls, phive tries to guess the version of the phar from the url. As this is not a phar url, phive fails at that, leading to the error message you got.

On top of that, the project you try to install does not provide any phars within their releases to begin with. If you think that should be different, please open a ticket with them as we cannot do anything about that.

Now if the project would provide a (signed) phar, you could have used `phive install deployphp/distribution`. But again, this won't work until they provide these phars.
