### ISSUE TITLE
Install Composer (globally) by phive

### ISSUE THREAD

**Issue by szepeviktor** [phar-io/phive#270]
Is there a reason why Composer cannot be installed by phive?

```
phive install --global --copy composer
```

resulting in `/usr/local/bin/composer`

**Comment by theseer** [comment]
The general statement is wrong, the above doesn't work for two reasons:

- There is no registered alias "composer", so the format "composer/composer" has to be used
- The composer developers choose not to sign their releases with gpg, so phive won't install it unless the lack of security is acknowledged by the user

That being said, the following will work:

`phive install --global --force-accept-unsigned composer/composer`

I'm not convinced though, given they do not provide independently verifiable signatures, using `phive` to install `composer` is any better than using their installer script. We might support additional signing means in a future version of `phive` and maybe then a trust chain can be established, but right now the signatures of composer releases are close to useless - at least from the perspective of `phive` if not generally.

**Comment by szepeviktor** [comment]
Thank you.

> The composer developers choose not to sign their releases with gpg

That is very-verry :( sad.
