### ISSUE TITLE
Get TravisCI to include phive by default

### ISSUE THREAD

**Issue by szepeviktor** [phar-io/phive#271]
Hello! Are there efforts to make phive available in TravisCI PHP images?

**Comment by szepeviktor** [comment]
BTW What is the current suggested solution to have phive ready in any CI without actually downloading it in every run?

**Comment by theseer** [comment]
> Hello! Are there efforts to make phive available in TravisCI PHP images?

Not as far as I am aware of.

I'm trying to understand how and if providing a "ready made" github action would be of interest to people though.

**Comment by theseer** [comment]
> BTW What is the current suggested solution to have phive ready in any CI without actually downloading it in every run?

As for everything: Use caching?

E.g. something like this in `.travis.yml`:

```
cache:
  directories:
  - "$HOME/.phive"
  - "$HOME/.phive/phars"

[...]

before_install:
- mkdir -p "$HOME/bin"
- export PATH="$HOME/bin:$PATH"
- if [ ! -d "$HOME/.phive" ]; then mkdir "$HOME/.phive"; fi
- if [ ! -f "$HOME/.phive/phive.phar" ]; then ant getphive; mv phive.phar "$HOME/.phive/"; fi
- install --mode=0755 -T "$HOME/.phive/phive.phar" "$HOME/bin/phive"
```

That will copy a previously or freshly downloaded `phive.phar` to `$HOME/bin/phive`. The only thing lagging in this example is automagic updating ;)

**Comment by szepeviktor** [comment]
I've started advertising phive on Travis :)

```yaml
cache:
  directories:
    - $HOME/.phive

before_install:
  - |
    # Download phive if not cached
    if [ ! -r "${HOME}/.phive/phive.phar" ]; then
        mkdir -p ~/bin
        if [ "$(phpenv version-name)" == 7.1 ]; then
            # phive v0.13.3 last version supporting PHP 7.1
            travis_retry wget -O "${HOME}/.phive/phive.phar" "https://github.com/phar-io/phive/releases/download/0.13.3/phive-0.13.3.phar"
            travis_retry wget -O "${HOME}/.phive/phive.phar.asc" "https://github.com/phar-io/phive/releases/download/0.13.3/phive-0.13.3.phar.asc"
        else
            travis_retry wget -O "${HOME}/.phive/phive.phar" "https://phar.io/releases/phive.phar"
            travis_retry wget -O "${HOME}/.phive/phive.phar.asc" "https://phar.io/releases/phive.phar.asc"
        fi
        travis_retry gpg --batch --keyserver ha.pool.sks-keyservers.net --keyserver-options timeout=10 --recv-keys 0x9D8A98B29B2D5D79
        if ! gpg --batch --verify "${HOME}/.phive/phive.phar.asc" "${HOME}/.phive/phive.phar"; then
            echo "Invalid phive signature" 1>&2
            rm -f "${HOME}/.phive/phive.phar"
            exit 11
        fi
        rm "${HOME}/.phive/phive.phar.asc"
    fi
  - install --verbose --mode=0755 -T "${HOME}/.phive/phive.phar" "${HOME}/bin/phive"
  - export PATH="${HOME}/bin:${PATH}"
  - travis_retry phive install --trust-gpg-keys ...,...,...
```

**Comment by theseer** [comment]
Looks very good! Thanks a lot!

I'm not yet sure how to best trigger updates of phive with this kind of setup. Unless you keep the cache, it will stay at whatever version you started with...

**Comment by szepeviktor** [comment]
> I'm not yet sure how to best trigger updates of phive

You add a periodic CI job :)

**Comment by theseer** [comment]
I consider travis-ci dead. Thus, will close this issue.

**Comment by szepeviktor** [comment]
> I consider travis-ci dead.

Yes, I've realized people do not use TravisCI as one has to ask for free open-source credits.
https://github.com/php-stubs/wordpress-stubs/blob/master/.travis.yml

There is no more to do! Just asking for credits.
