### ISSUE TITLE
List of all aliases?

### ISSUE THREAD

**Issue by Ilyes512** [phar-io/phive#276]
Where can I find a list of all available aliases? Can someone also point/hint me to the "manifest" file? I couldn't find that either.

**Comment by Ilyes512** [comment]
Never mind! I second after posting this I noticed the command `phive update-repository-list` and the link to https://phar.io/data/repositories.xml

**Comment by theseer** [comment]
`phive list` would have also helped.

**Comment by Ilyes512** [comment]
Ah, I thought that would list currently installed packages.

BTW, I have decided to not use phive and just use composer global as I do now in my containers. One of the reasons was not being able to install sensiolabs/security-checker:

```bash
phive install sensiolabs/security-checker --force-accept-unsigned
```

**Comment by theseer** [comment]
They do not provide phar releases - or if they do, it's not visible to phive in any way -, so even forcing to accept unsinged releases doesn't work.

Feel free to open a bug report at that project.

**Comment by Ilyes512** [comment]
FYI, I think it used to work: https://github.com/sensiolabs/security-checker/issues/132#issuecomment-432637151

But they (sensionlabs) seem to be pushing their `symyfony cli`-tool which does not make sense for me (when working on Laravel based apps).

**Comment by theseer** [comment]
While the comment indeed mentions it, it can never have worked that way. There has never been a phar attached to any release in github, let alone a signature.

All they provide is an inline link in the `README` which points to some arbitrary url off of github.

I'm not sure if they see the irony in providing a security tool - without any security for its installation.
