### ISSUE TITLE
Your environment is not ready to run phive due to the following reason(s)

### ISSUE THREAD

**Issue by renakdup** [phar-io/phive#277]
Hi, after install as have written in docs. I have error:

```
phive
[ERROR]    Your environment is not ready to run phive due to the following reason(s): 
[ERROR]     
[ERROR]              ext/dom not installed/enabled 
[ERROR]              ext/mbstring not installed/enabled 
[ERROR]              ext/curl not installed/enabled 
[ERROR]     
```

**Comment by theseer** [comment]
So where's the bug in this?

Your environment is obviously missing required extensions. `phive` tests for that and complains in case required ones are missing. 

Nothing we can do to fix your environment. Install the missing extensions and you're good to go.
