### ISSUE TITLE
When the package version only has major and minor parts, phive copies to incorrect file

### ISSUE THREAD

**Issue by ArtemGoutsoul** [phar-io/phive#279]
When installing a package with a version package-X.Y.Z, it's copied to /usr/local/bin/package
```
# phive --no-progress install -g psalm@3.14.2
Phive 0.13.2 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
Copying psalm-3.14.2.phar to /usr/local/bin/psalm
```
When installing a package with a version package-X.Y. it's copied to /usr/local/bin/package-X.Y
```
# phive --no-progress install -g psalm@3.16
Phive 0.13.2 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
Copying psalm-3.16.phar to /usr/local/bin/psalm-3.16
```

**Comment by theseer** [comment]
You're using an outdated version of `phive`. Please upgrade to 0.14.4+.

**Comment by ArtemGoutsoul** [comment]
thanks!

I also switched to installing using the XML fie instead of installing each tool separately.

would be nice to have version specification separately from installed files info, this way phive.xml more friendly for living in git. will try to understand the logic of this a bit better before filing an issue though.

**Comment by theseer** [comment]
The logic is simple: There is no point in splitting constraints from installed info as you'll be checking in both anyway (like, for instance composer.json and composer.lock) and we do not have a gigantic dependency tree to resolve which we'd have store. So, having a second file just to store a version identifier?
