### ISSUE TITLE
Using phive in GitHub Actions

### ISSUE THREAD

**Issue by szepeviktor** [phar-io/phive#282]
This is my first try on GitHub Actions https://github.com/szepeviktor/phive-action-example

1. installs PHIVE
1. runs `phive install`

**Comment by szepeviktor** [comment]
Already available on the Marketplace: https://github.com/marketplace/actions/install-phar-files

**Comment by theseer** [comment]
Looks very promising! :+1:

**Comment by szepeviktor** [comment]
Thank you for your kind words.

The thing is Travis CI is simple and has more features.

**Comment by pattisahusiwa** [comment]
`phive` is already included in [`shivammathur/setup-php`](https://github.com/marketplace/actions/setup-php-action#wrench-tools-support) github actions.

**Comment by szepeviktor** [comment]
At the first glance that action does not check the signature of phive.phar :(

**Comment by pattisahusiwa** [comment]
Sorry, but I've no idea about that.

It's fine as long as the correct version of tools are installed and I can use the tools.

**Comment by theseer** [comment]
No worries. Just wrote this for clarification.

**Comment by szepeviktor** [comment]
The "V" in PHIVE means _Verification_ :)

**Comment by pattisahusiwa** [comment]
Ok, that's not a problem anymore as you've mentioned above :)

https://github.com/szepeviktor/phive/blob/478682ab6ea15fc162b58c9468cfb0b603afea43/run.sh#L47-L53
