### ISSUE TITLE
Please add kint-php/kint to repositories.xml

### ISSUE THREAD

**Issue by burzum** [phar-io/phive#283]
I would like to install https://github.com/kint-php/kint via phive. They already provide a phar archive. When I try to install it I get this error:

```sh
php .\phive.phar install https://raw.githubusercontent.com/kint-php/kint/master/build/kint.phar
Phive 0.14.4 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]   Could not extract PHAR version from https://raw.githubusercontent.com/kint-php/kint/master/build/kint.phar
```

Or how can I add an existing phar file of a project to the repositories? I don't mind helping just tell me how to do so. :) Has the maintainer of the project to do something?

**Comment by theseer** [comment]
As the error message already suggests, when using a plain http URL, `phive` needs to extract the version information from the filename. As that URL's filename does not contain any such information, `phive` has no means of knowing which version that is and whether or not it's an update for an already installed phar. We thus decided to not support this type of installation. If you disagree, feel free to open a ticket and propose a solution ;)

To be able to install `kint` with phive, indeed chances are the maintainer(s) has to do something. Please read or have them read https://phar.io/distribute-your-own.html. If there are any further questions, just ask / have them asked.
