### ISSUE TITLE
Use --option instead of -option

### ISSUE THREAD

**Issue by sebastianbergmann** [phar-io/phive#29]

**Comment by sebastianbergmann** [comment]
After fcdcf190b048aa7a4bb64d1a2996bdbbf8e55b7d there now is `--target` but the other options still use a single `-`. This is inconsistent :-)

**Comment by theseer** [comment]
Redoing the CLI parsing is planned but was not considered important enough for this release.

**Comment by theseer** [comment]
Fixed with commit 4e71c841a1faae485edbb096b707c8c2e9ce4183
