### ISSUE TITLE
Handle clash of `$HOME/.phive` and `$CWD/.phive`

### ISSUE THREAD

**Issue by theseer** [phar-io/phive#290]
Currently, phive can't properly work with $HOME and $CWD being identical as the sub directory `.phive` clashes.

We need to find a way to deal with this.

**Comment by vertexvaar** [comment]
Hi,

i discovered phive when searching for a tool to get rid of composer dev-dependency issues with development/quality tools.
This tool is quite nice, but there's one itch i can't scratch, which also targets this issue.
I'd like to be able to define where the file `phars.xml` is stored, including the folder where it's stored.

It is common style to provide an option to define the location of the configuration file (see phpmd, phpcs, phpstan, etc...). Also, the default among all tools is to have a single file in the project root.
IMHO it is nicer to have a single dot-file named after the tool (`.phive.xml`) in the project root.

Having an option to define the location/name of the `phars.xml` file could also solve this issue.

Regards

**Comment by theseer** [comment]
Having an option might be indeed a nice addition.

Phive though does support having a single file in the project root: `phive.xml`. Only if that file is not present, phive by default will store things in a *folder*, as multiple files may be required for different usage scenarios and we do not want to clutter the project root with multiple files.

That's actually quite new as before we only had that single file.

**Comment by theseer** [comment]
When `phive` was started with the current work directory and home directory being identical, the diretory `~/.phive` is used for local (project specific) files as well as as phive's home directory. 

That is not actually a problem, but the migration code - trying to rename the home directory `phars.xml` got confused as it didn't realize that `phars.xml` can also be the valid project specific file.

This got fixed and will be included in the next release.
