### ISSUE TITLE
GPG warning?

### ISSUE THREAD

**Issue by mkoske** [phar-io/phive#308]
Hello,

while verifying phive.hpar, I get this warning:

gpg WARNING: This key is not certified with a trusted signature!

Why is this?

**Comment by theseer** [comment]
### Short answer

Your question shows you didn't read the 2nd line of the warning. For it to go away, you'd have set a higher trustlevel to it.

### Long answer

I assume you followed the instructions from our website (https://phar.io/#Install).

The line `gpg --keyserver pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79` imports our public gpg key - whose private key is used for signing - into your key ring. That's an expected and I hope understandable prerequisite to verifying a signature - like in the next step.

While for a verification of a signature this is perfectly good enough - we just want to ensure the signature is correct here -, from gnupg's perspective there has not been any verification that the used key belongs to us. You'd have to compare the fingerprint shown in line 3 of the output with the one published on our website and in case you find it correct, sign the key with a trusted one - for instance your own. That why, gnupg knows that the identity has been verified and to trust the key.

While that in general is a good practice, it's okay to not do this when you merely want to check signatures like we suggest on our initial install. Once using phive, phive will ask you to verify the keys it downloaded before trusting them.
