### ISSUE TITLE
GPG Warning when upgrading psalm

### ISSUE THREAD

**Issue by toby-griffiths** [phar-io/phive#309]
I've just tried to upgrade psalm but I'm receiving a warning that the key is not the same as previously used.

I'd like to confirm this is OK, but am not sure how to.  How do I go about confirming whether this is a valid, new key for the signed phar?

Here's the shell output

```shell
❯ phive update psalm
Phive 0.14.5 - Copyright (C) 2015-2021 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://github.com/vimeo/psalm/releases/download/4.7.1/psalm.phar
Downloading https://github.com/vimeo/psalm/releases/download/4.7.1/psalm.phar.asc
Downloading key 12CE0F1D262429A5
Trying to connect to keys.openpgp.org (37.218.245.50)
Downloading https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0x12CE0F1D262429A5
Successfully downloaded key.
[WARNING]  This is NOT a key that has been used to install previous versions of this PHAR.
           While this can be perfectly valid (maybe the maintainer switched to a new key),
           please make sure this key belongs to the maintainer of the PHAR you are going to install.

        Fingerprint: 2DE5 0EB6 0C01 3FFF A831 040D 12CE 0F1D 2624 29A5

        Matthew Brown (Key for signed Psalm phars) <github@muglug.com>

        Created: 2021-01-11
```

Please excuse any incorrect terminology.  I don't have much prior knowledge of GPG signing.

**Comment by theseer** [comment]
Is this happening on an interactive CLI prompt? Because if so, it should have provided you with an input option.

For CI/CD, without an interactive shell, this is a bit tricky as I believe we currently do not allow/support passing in trusted keys via cli parameters with update and/or changing keys. Best bet for CI/CD is to remove the cache and run `phive install --trust-gpg-keys 0x12CE0F1D262429A5,....` to install the state as given in `phive.xml`.

**Comment by theseer** [comment]
Ping?

**Comment by toby-griffiths** [comment]
Sorry @theseer.  i've actually forgotten which project I had this issue on, but for reference, where do I go to find valid gpg keys for the developer, so that I can use the `--trust-gpg-keys` flag?

**Comment by theseer** [comment]
That of course depends on the project and how they publish this information.

We, for example, publish our key id and fingerprint on our project page in the footer.

**Comment by toby-griffiths** [comment]
Ah, OK.  Thanks for the info.
