### ISSUE TITLE
`phive install` installs a pre-release

### ISSUE THREAD

**Issue by NicoHaase** [phar-io/phive#313]
For https://github.com/drud/ddev/pull/3009, we ran into a strange problem: when executing `phive install platformsh/platformsh-cli`, a pretty old pre-release is installed, instead of the latest stable release that is just some days onld

This is the version that gets installed: https://github.com/platformsh/platformsh-cli/releases/tag/v4.1.0-dev (released on June 09th 2019), and since then, a lot of later stable versions (with a lower version number!) have been released. 

When searching for this version in https://api.github.com/repos/platformsh/platformsh-cli/releases?per_page=100, I see that a flag `prerelease: true` is set on that release. Would it be possible to enhance Phive, such that releases with such a flag set to `true`  are ignored in the default case?

**Comment by theseer** [comment]
Yes and no.

I indeed agree we should have a switch for "only stable versions", explicitly excluding everything with a pre-release suffix like `dev`, `rc` or `alpha`. Not sure if that should be default? And, either way, when would that default apply and when not? Only when no version constraint is given? Additionally, what about `0.x.y`? Is that considered a pre-release?


Pinning all that to to github's prerelease-flag is a different story, as we do support other providers than just github and I so far do not like the idea of adding flags that only work with one of them.

**Comment by theseer** [comment]
Actually, we already have an issue for this: #154 .
