### ISSUE TITLE
"Broken cURL install" message is not being displayed

### ISSUE THREAD

**Issue by jrfnl** [phar-io/phive#327]
Follow up on #143 which reported the following error message:
```
[ERROR]    Unexpected HTTP error: SSL certificate problem: unable to get local issuer certificate (while requesting https://phar.io/data/repositories.xml) (Code: 60)
```

Quoting @theseer, the error can be solved by:
> One potential way to fix this is by downloading the cacert.pem provided by CURL and setting its path in the `php.ini` by having it contain `curl.cainfo="/path/to/downloaded/cacert.pem"`.

And I can confirm that doing so solves the issue.

An additional, more informative error message was added in https://github.com/phar-io/phive/commit/74a2f55fc7beefa8cbbf1fd43b5f207dabed589b

However that message does not display (which is why I went searching for more info in the issues and found issue #143).

Discovered while running on PHP 7.4.21 with Phive 0.15.0.

![image](https://user-images.githubusercontent.com/663378/128179707-814d6e8f-6f6f-4e57-83e2-a9a303f65077.png)

**Comment by theseer** [comment]
That - of course - was a rather stupid bug ;)

Thanks @jrfnl!

**Comment by jrfnl** [comment]
😂 Aren't the majority ? Thanks @theseer for your swift action!
