### ISSUE TITLE
v0.15.0 depends php-xml?

### ISSUE THREAD

**Issue by CNSKnight** [phar-io/phive#330]
installing/using Phive on a new box and seems to depend on ext/xml (as eg php-xml, or as required php7.4-xml, php8.0-xml) on run - but I found no mention in the README

**Comment by theseer** [comment]
Phive uses `phar-io/manifest`, which uses `libxml`'s method for proper error handling.

With commit 0dfdb86a2cee9bde69ba15f8deddc850808a7008 phive now checks for this extension.
