### ISSUE TITLE
Unknown option: home

### ISSUE THREAD

**Issue by ricardoboss** [phar-io/phive#359]
I ran `phive install --home /my/path` with the following result:

```
Phive 0.15.0 - Copyright (C) 2015-2022 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]   Error while processing arguments to command 'install':
[ERROR]   Unknown option: home
```

I also tried setting it via the config:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phive xmlns="https://phar.io/phive">
  <config home="/my/path" />
</phive>
```

This had no effect.

How do I set a custom home option?

**Comment by ricardoboss** [comment]
Is this also possible via the config?

**Comment by theseer** [comment]
No.  We should probably add that to the list of things that might be of interest to be configurable.
