### ISSUE TITLE
Installing phpunit fails

### ISSUE THREAD

**Issue by jakzal** [phar-io/phive#369]
Steps to reproduce:

```
$ phive --no-progress --home /usr/local/bin/.phive install --trust-gpg-keys 4AA394086372C20A phpunit -t /usr/local/bin/.phive/bin
Phive 0.15.1 - Copyright (C) 2015-2022 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://phar.phpunit.de/phive.xml
[ERROR]   Failed to download load https://phar.phpunit.de/phive.xml: HTTP Code 403
```

**Comment by theseer** [comment]
Thank you for taking time to report an issue. This is not a problem with phive though.

Please check these tweets for details:
- https://twitter.com/arneblankerts/status/1526900441296019456
- https://twitter.com/arneblankerts/status/1527206545032986625
