### ISSUE TITLE
Provide GitHub auth token in a file

### ISSUE THREAD

**Issue by ciaranmcnulty** [phar-io/phive#372]
When using phive inside a `docker build` there's currently not a way of securely providing a GitHub authentication token. Using the `GITHUB_TOKEN` env var means that is inspectable in the resulting image. 

If Phive could read the secret from a file, then [build secrets](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#run---mounttypesecret) could be used and we could build images faster without worrying about rate limiting.

**Comment by theseer** [comment]
Did you give `phive skel -a` a try?  It should generate a skeleton `auth.xml` for you, that can contain arbitrary credentials for domains and hostnames. Supporting bearer and token auth as well as traditional basic auth, this might already be what you are looking for.

It's not exactly what you asked here though.

**Comment by ciaranmcnulty** [comment]
No but I'll check it out, thank you

**Comment by theseer** [comment]
Quick heads up:

I'm working on optimizing the auth handling - and found some issues in the current implementation with the `auth.xml` files.
I'll try to have a new release ready soon which will include a better (and fixed) version.

**Comment by ciaranmcnulty** [comment]
This seems to work for me thank you

**Comment by ciaranmcnulty** [comment]
So it doesn't work for me ;)

In `jakzal/toolbox` it supplies `--home` to install phars in a bunch of different temp folders, then copy them out

It'd be good to have something like an env var pointing to the file that overrides the search location if set, or a similar mechanism
