### ISSUE TITLE
Can Apigen be added?

### ISSUE THREAD

**Issue by salarmehr** [phar-io/phive#376]
Can https://github.com/ApiGen/ApiGen be added to the supported tools?

**Comment by theseer** [comment]
I'm not sure what you mean by "supported":

- If you want an alias (e.g. `apigen`), make the project maintainers sent a PR to our registry
- If you want to be able to install via `phive install apigen/apigen`, make the project maintainers sign their release phar
- If you don't mind it's not signed, use `phive install --force-accept-unsigned apigen/apigen` to install.

There's nothing we can do here.
