### ISSUE TITLE
https://phar.io/phive 404

### ISSUE THREAD

**Issue by dangoodman** [phar-io/phive#407]
phive.xml schema – https://phar.io/phive – is not available

Could not find any description of the phive.xml format. How do I configure a custom tools dir location?

**Comment by dangoodman** [comment]
Thank you for the quick response.

I believe publishing the schema at https://phar.io/phive might help people to self-discover the available configuration options (case 3). Especially considering the modern IDEs' autocompletion for XML documents with a downloadable schema.

**Comment by theseer** [comment]
I agrree.
