### ISSUE TITLE
Wrong versions installed if done via Github Actions

### ISSUE THREAD

**Issue by LordSimal** [phar-io/phive#411]
Hey there phive developers! Really appreciate the time and work that has been put into this awesome tool!

But recently we have run into a weird problem related to phive installing not the specified version from `.phive/phars.xml`

The Github Actions config I am talking about can be seen here: 
https://github.com/cakephp/.github/blob/5.x/.github/workflows/cs-stan.yml

But this is just a template config which is used by many other repositories of ours, like e.g. here:
https://github.com/cakephp/cakephp/blob/5.x/.github/workflows/ci.yml#L208-L212

Locally `phive install` works as intended and installs `phpstan 1.10.14` and `psalm 5.10.0` as defined in:
https://github.com/cakephp/cakephp/blob/5.x/.phive/phars.xml

But not inside CI as you can see here:
https://github.com/cakephp/cakephp/actions/runs/5380672968/jobs/9764022048?pr=17172#step:5:19

Both CI and locally we are using phive 0.15.2 so it can't be related to a version difference there.

Do you have any idea why this happens? Its not like phive can't read the `.phive/phars.xml` file because phpstan and psalm are being installed, just not in the correct version.

**Comment by theseer** [comment]
I don't think there is anything wrong on phive's end here.

The linked CI run is operating on the Pull Request #17172, which is setting the tools to exactly the versions installed.

https://github.com/cakephp/cakephp/pull/17172/files#diff-bf3b5b5e32d0c7e309995719d0c867d3fecb8b62dd9d0646f1e99becdb4e3367

Or am I missing anything?

**Comment by LordSimal** [comment]
I am so sorry... 🙈
Everything works as intended. I just missed that the PR changes the used versions.
Thanks for looking into this so quickly 🙇
