### ISSUE TITLE
Use Phive to download Composer?

### ISSUE THREAD

**Issue by MacDada** [phar-io/phive#413]
This is the script  that currently downloads Composer into my project:

```sh
#!/bin/sh

# https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md

EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
then
    >&2 echo 'ERROR: Invalid installer checksum'
    rm composer-setup.php
    exit 1
fi

php composer-setup.php --quiet
RESULT=$?
rm composer-setup.php
exit $RESULT
```

Is is a good idea to get rid of the script above -> and download Composer using Phive?

It makes logical sense to me, as Composer is just "yet another tool" that my project needs, while Phive is the tool to manage project tools.

I'm sensing that there might be some kind of downside, as the Phive project itself is _not_ doing that [?]:

* Composer is not listed in [phive.xml](https://github.com/phar-io/phive/blob/22e35df41b7a1fb12c6cf3682e9370d594427167/phive.xml)
* Although, apparently, it is being used from the `tools` folder in [build.xml](https://github.com/phar-io/phive/blob/22e35df41b7a1fb12c6cf3682e9370d594427167/build.xml#L127)

So, another question would be: how does Composer get into the `tools` dir, while not being downloaded by Phive? And why not? Am I missing something?

**Comment by theseer** [comment]
`phive install composer` :-)

**Comment by MacDada** [comment]
> `phive install composer` :-)

yep, I know I can do that… I wanna do that… but my questions remain :P

1. Are there any downsides (compared to my downloading script)?
2. Why the Phive project itself is not doing that? Or is it?

**Comment by MacDada** [comment]
> I'm not sure I understand why people even bother checking a hash.

The script is what Composer recommends in its docs: https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md#how-do-i-install-composer-programmatically-

> phive's approach is superior to that simple download script

Cool. Go Phive! 👍 

> Phive isn't using itself to install composer simply because I never updated the build setup properly.

That's what I suspected, but it never hurts to ask to be sure. Thanks!

**Comment by theseer** [comment]
I know they (still) advertise it. That doesn't make it any less pointless ;-)
