### ISSUE TITLE
Error while executing: Preparing php v8.4.0

### ISSUE THREAD

**Issue by mpcleverdon** [phar-io/phive#431]
trunk_cli_version: 1.22.3
title: "Error while executing: Preparing php v8.4.0"
report:
  - command: |
      /Users/mpcleverdon/.cache/trunk/tools/phive/0.15.1-f6c8fdb9a4b04d65ad41bea5ad397f64/phive install --trust-gpg-keys CBB3D576F2A0946F --target /Users/mpcleverdon/.cache/trunk/tools/composer/2.5.1-4dc2fb99b6a9cd829633abb859a78925 composer@2.5.1
    stdin_path: (none)
    run_from: /Users/mpcleverdon/.cache/trunk/tools/phive/0.15.1-f6c8fdb9a4b04d65ad41bea5ad397f64
    timeout: 10m
    rerun: (cd /Users/mpcleverdon/.cache/trunk/tools/phive/0.15.1-f6c8fdb9a4b04d65ad41bea5ad397f64; env -i HOME=/Users/mpcleverdon 'PATH=/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/mpcleverdon/Library/Application Support/cloud-code/installer/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/opt/openjdk@17/bin:/usr/local/opt/curl/bin:/Users/mpcleverdon/google-cloud-sdk/bin:/Users/mpcleverdon/.npm-packages/bin:/Users/mpcleverdon/.cache/trunk/launcher' USER=mpcleverdon SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.FB3ozgCFC0/Listeners /Users/mpcleverdon/.cache/trunk/tools/phive/0.15.1-f6c8fdb9a4b04d65ad41bea5ad397f64/phive install --trust-gpg-keys CBB3D576F2A0946F --target /Users/mpcleverdon/.cache/trunk/tools/composer/2.5.1-4dc2fb99b6a9cd829633abb859a78925 composer@2.5.1)
    exit_status: exited
    exit_code: 10
    stdout: |

      Deprecated: PharIo\Phive\Factory::__construct(): Implicitly marking parameter $version as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/mpcleverdon/.cache/trunk/tools/phive/0.15.1-f6c8fdb9a4b04d65ad41bea5ad397f64/phive/src/Factory.php on line 35

      Deprecated: PharIo\Phive\Cli\Runner::showErrorWithTrace(): Implicitly marking parameter $trace as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/mpcleverdon/.cache/trunk/tools/phive/0.15.1-f6c8fdb9a4b04d65ad41bea5ad397f64/phive/src/shared/cli/Runner.php on line 140

      Deprecated: PharIo\Phive\Config::__construct(): Implicitly marking parameter $now as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/mpcleverdon/.cache/trunk/tools/phive/0.15.1-f6c8fdb9a4b04d65ad41bea5ad397f64/phive/src/shared/config/Config.php on line 34
      Phive 0.15.1 - Copyright (C) 2015-2024 by Arne Blankerts, Sebastian Heuer and Contributors

    stderr: |
      PHP Deprecated:  PharIo\Phive\Factory::__construct(): Implicitly marking parameter $version as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/mpcleverdon/.cache/trunk/tools/phive/0.15.1-f6c8fdb9a4b04d65ad41bea5ad397f64/phive/src/Factory.php on line 35
      PHP Deprecated:  PharIo\Phive\Cli\Runner::showErrorWithTrace(): Implicitly marking parameter $trace as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/mpcleverdon/.cache/trunk/tools/phive/0.15.1-f6c8fdb9a4b04d65ad41bea5ad397f64/phive/src/shared/cli/Runner.php on line 140
      PHP Deprecated:  PharIo\Phive\Config::__construct(): Implicitly marking parameter $now as nullable is deprecated, the explicit nullable type must be used instead in phar:///Users/mpcleverdon/.cache/trunk/tools/phive/0.15.1-f6c8fdb9a4b04d65ad41bea5ad397f64/phive/src/shared/config/Config.php on line 34
      [ERROR]   An error occurred while processing your request:

                PharIo\Phive\XmlFile::query(): Implicitly marking parameter $ctx as nullable is deprecated, the explicit nullable type must be used instead
                
                #0 src/shared/XmlFile.php(71)
                #1 (347): PharIo\Phive\Cli\Runner->errorHandler()
                #2 (347): require()
                #3 src/Factory.php(438): {closure:/Users/mpcleverdon/.cache/trunk/tools/phive/0.15.1-f6c8fdb9a4b04d65ad41bea5ad397f64/phive:27}()
                #4 src/Factory.php(97): PharIo\Phive\Factory->getPhiveXmlConfig()
                #5 src/commands/CommandLocator.php(42): PharIo\Phive\Factory->getInstallCommand()
                #6 src/shared/cli/Runner.php(241): PharIo\Phive\CommandLocator->getCommand()
                #7 src/shared/cli/Runner.php(95): PharIo\Phive\Cli\Runner->execute()
                #8 (354): PharIo\Phive\Cli\Runner->run()
                #9 {main}

                Environment: PHP 8.4.0-dev (on Darwin 23.6.0)
                Phive Version: 0.15.1

                This should not have happened and is most likely a bug.
                Please report it at https://github.com/phar-io/phive/issues, make sure you include
                the full output of this error message. Thank you!

      [ERROR]   An error occurred while processing your request:

                PharIo\Phive\Config::__construct(): Implicitly marking parameter $now as nullable is deprecated, the explicit nullable type must be used instead
                
                #0 src/shared/config/Config.php(34)
                #1 unknown file(0): PharIo\Phive\Cli\Runner->shutdownHandler()
                #2 {main}

                Environment: PHP 8.4.0-dev (on Darwin 23.6.0)
                Phive Version: 0.15.1

                This should not have happened and is most likely a bug.
                Please report it at https://github.com/phar-io/phive/issues, make sure you include
                the full output of this error message. Thank you!

**Comment by theseer** [comment]
Fixed in 0.15.3.

For the record: version 0.15.1 was outdated.
