### ISSUE TITLE
--target does not work

### ISSUE THREAD

**Issue by sebastianbergmann** [phar-io/phive#51]
```
$ phive install --target /tmp phpunit
Phive 0.3.0 - Copyright (C) 2015-2016 by Arne Blankerts, Sebastian Heuer and Contributors
[ERROR]    Setting mode for directory "/tmp" failed.
```

**Comment by theseer** [comment]
While one might argue that trying to change the mode of an already existing directory could be considered a stupid idea, the fact you cannot adjust perms of /tmp is actually expected.
