### ISSUE TITLE
version syntax

### ISSUE THREAD

**Issue by m8rge** [phar-io/phive#67]
Why version syntax isn't like in composer: `vendor/package:2.*` or docker `ubuntu:14.04`? Why `@` sing, not `:`?

**Comment by theseer** [comment]
The version *syntax* is composer compliant, just the separator for the command line call is different.
I personally like the ```@```-sign as a separator, but arguably we could support alternative separators. Dnf/yum or apt-get for instance use ```-``` or ```=``` respectively. 

We'll consider that.

**Comment by belanur** [comment]
I see no problem in adding support for alternative separators like `:`. By the way: the `@` is used by [npm](https://www.npmjs.com/), that's where we took it from ;)

**Comment by theseer** [comment]
Phive now supports ```:```, ```=``` and ```@``` as separator.
