### ISSUE TITLE
Implement self update

### ISSUE THREAD

**Issue by belanur** [phar-io/phive#7]
By running ```phive selfupdate``` PHIVE should download the most recent version of the PHIVE PHAR from phar.io and replace the current active version with it. 

Before downloading the PHAR, the SSL certificate of https://phar.io must be validated against the cainfo file from the currently active PHAR . Only it the certificate has been signed by the expected CA authority (and is generally valid), the update will start.

**Comment by sagikazarmark** [comment]
Would be nice to provide a toolkit for PHARs for self-updating using the phar.io repository.

**Comment by theseer** [comment]
@sagikazarmark That's an awesome idea. I'll move that into its own issue though.

**Comment by xyNNN** [comment]
It would make sense to standardize it and name it like composer does, or? So we should call the command ```phive self-update```instead of ```phive selfupdate```

By the way, great talk today at IPC 2016 Spring Edition in Berlin @belanur @theseer 👍

**Comment by sagikazarmark** [comment]
I think composer works with both.

**Comment by xyNNN** [comment]
Yeah, you're right @sagikazarmark, my fault! Then phive should support the two ways or the better option ```self-update```. I'm a fan of convention and standards. Especially the PHP community worked hard for several standards in the last years, we as developers should support it :)

**Comment by sagikazarmark** [comment]
Standards are great to provide compatibility between things. The "things" in this case are the user interface and the user itself, so I would say this is rather a convenience thing than something that worth standardization.

Apart from the reasoning above, I 100% agree. :smile:

**Comment by xyNNN** [comment]
You know what I mean, so we're fine with that 👍 ;)
