### ISSUE TITLE
Check if running environment supports colored output

### ISSUE THREAD

**Issue by belanur** [phar-io/phive#80]
Currently `UnixoidEnvironment::supportsColoredOuput()` always returns `true` without really verifying that the current environment does actually support colors. This should be determined on runtime, maybe using `tput colors`.

**Comment by dnaber-de** [comment]
Nice labeling to guide possible new contributors :+1: I'll start to put some effort on this the next days…

**Comment by sebastianbergmann** [comment]
You may want to have a look at https://github.com/sebastianbergmann/environment/blob/master/src/Console.php#L29

**Comment by dnaber-de** [comment]
From `SebastianBergman\Environment\Console::hasColorSupport()`:

```
    if (DIRECTORY_SEPARATOR == '\\') {
        return false !== getenv('ANSICON') || 'ON' === getenv('ConEmuANSI') || 'xterm' === getenv('TERM');
    }
```
Is that for Windows OS? If so, it could be a possible implementation for `WindowsEnvironment::supportsColoredOutput()` which currently returns always `false`.
