### ISSUE TITLE
Support for SHA512 and SHA384

### ISSUE THREAD

**Issue by piotr-zuralski** [phar-io/phive#90]
In docs there is support for SHA512 but no support for it in the code, and some other phars has only SHA384 provided

**Comment by theseer** [comment]
The subject of this ticket is not exactly clear:

- **For file hashes**
The phar.io Repository allows to specify hashes for files as SHA-1, SHA-256, SHA-384 and SHA-512. Other repository types - like github releases - do not publish these and are thus not supported there.
Phive checks the hash when supplied.

- **As signature**
A plain SHA* is not a cryptographically secure signature as it does not require a private key for creating it

- **OpenSSL Digest**
A secure SHA*-signature can be created with OpenSSL but automating verification in a generic way is close to impossible - see #111 for details.

**Comment by piotr-zuralski** [comment]
@theseer it was revelant until Apr 24, 2017 as the [feb7788031f1de362c8687f9e218b4f97be9fad0](https://github.com/phar-io/phive/commit/feb7788031f1de362c8687f9e218b4f97be9fad0#diff-461cb0f1c5ef38e9af56cc9bdc97f63e) introduced hashes for SHA-384 and SHA-512.

**Comment by theseer** [comment]
Thanks for the update.
