### ISSUE TITLE
Why a new dependency manager / package manager / installer?

### ISSUE THREAD

**Issue by christian-weiss** [phar-io/phive#93]
Ok, ok, sure, installing PHAR tools globally and linking them at project level is clever, but do we really need another dependency manager / package manager / installer for that?

Please, please, please consider to move phive code to a composer 'custom installer plugin'. A PHAR installer plugin for composer. Downloading to a user home dir and symlinking can be done there, too. A phar release should contain a composer.json for that phar project. This composer.json should required your custom phar installer plugin to download, install to user home dir and symlink it.

See: https://getcomposer.org/doc/articles/custom-installers.md for details on custom installers
You do not need to re-implement all the things dependency manager should do (caching, lock file, etc.) when you implement phive as a custom installer plugin for composer. And there is a good tooling support for composer already (IDE and ecosystem).

e.g. 
https://github.com/sensiolabs/security-checker
https://github.com/clue/graph-composer

I see the need for phive, but not as a separate dependency manage, when we already have good dependency managers.

**Comment by theseer** [comment]
We already have a ticket to integrate into composer (see #12). It will come when we have stabilized the main application.  The idea there is to "fix" the require/require-dev mess by filtering out entries that we know about and install them via phive. The API available for custom installers is a pita though and barely provides enough control for what we need.

A composer.json for a phar release is superfluous as it contains a lot of information required for *resolving* a dependency. That's the wrong end of the stick from a phar's perspective as the phar *contains* those dependencies. We thus created our own manifest format, see [phar.io/manifest example](https://github.com/phar-io/manifest/blob/master/tests/_fixture/phpunit-5.6.5.xml). 

Regarding your last point:
Phive is *not* a dependency manager and it doesn't try to be one. It's a simple tool to automate the steps required to securely install tools that are shipped as a phar. And uses some maybe clever approaches to avoid re-downloading half the internet to accomplish that.

The only sort-of dependency future versions of phive are likely to check - in case a phar.io manifest can be found - is the PHP version and required extensions.

**Comment by belanur** [comment]
In the current state this is "won't fix" for us, so we close the issue - but we will happily continue the discussion.
