### ISSUE TITLE
Check PHAR's requirements during installation

### ISSUE THREAD

**Issue by belanur** [phar-io/phive#94]
Use [phar-io/manifest](https://github.com/phar-io/manifest) to parse the manifest of a PHAR after download and to extract the required PHP version as well as required extensions. 

In interactive mode, the user should be notified of unmet requirements and asked if he still wants to install the PHAR. 

In non-interactive mode, the user should still be notified, but the PHAR will automatically be installed.

**Comment by theseer** [comment]
Implemented.
