### ISSUE TITLE
phive.xml always updated

### ISSUE THREAD

**Issue by KingCrunch** [phar-io/phive#96]
I want to create a `Makefile`, but  even `phive install` updates `phive.xml` on every run. This means from `make`s point of view the tools are always expired. Since there is no lock file (see #92 ) `phive.xml`s timestamp should not change, when the file itself does not change.

**Comment by theseer** [comment]
The install command currently does not check whether the symlink in the tools directory is already present/points to the requested version but merely (re-)creates it.

As a result, the phive.xml gets "updated" - even though nothing actually changed from a content perspective.
